import streamlit as st
import random

# ---------------------------
# Fragen und Antworten laden
# ---------------------------
questions = [
    
    {"question": "1.1 a) Das Pricing ist deshalb von besonderer Bedeutung im Marketing-Mix, weil es einen indirekten Einfluss auf die Unternehmenskennzahlen hat.", "answer": "falsch", "explanation": "Pricing beeinflusst Umsatz und Gewinn direkt, nicht nur indirekt."},
    {"question": "1.1 b) Der Kompromisseffekt beschreibt den Effekt, dass Konsumenten einen Referenzpreis zur Preisbeurteilung heranziehen.", "answer": "falsch", "explanation": "Das beschreibt den Ankereffekt, nicht den Kompromisseffekt."},
    {"question": "1.1 c) Der Preisankereffekt beschreibt, dass Kund:innen, bei einer Vielzahl von Produkten mit unterschiedlichen Preisen innerhalb einer Produktlinie, Produkte in mittlerer Preisklasse wählen.", "answer": "falsch", "explanation": "Das ist der Kompromisseffekt, nicht der Preisankereffekt."},
    {"question": "1.1 d) Eine Edelstahl-Trinkflasche kostet CHF 10, die variablen Produktionskosten entsprechen CHF 2 pro Stück und die Fixkosten CHF 10'000. Von den Trinkflaschen verkaufen Sie 5'000 Stück. Der resultierende Gewinn beträgt CHF 20'000.", "answer": "falsch", "explanation": "Gewinn = 5000*10 - (5000*2 + 10000) = CHF 30'000."},
    {"question": "1.2 a) Die drei Elemente des 'Magischen Dreiecks des Pricings' sind: kundenorientierte Preise, vergangenheitsorientierte Preise und wettbewerbsorientierte Preise.", "answer": "falsch", "explanation": "Statt vergangenheitsorientiert ist kostenorientiert korrekt."},
    {"question": "1.2 b) Die Übervorteilungsstrategie im Rahmen der Preispositionierung entspricht einer hohen Qualität zu tiefen Preisen.", "answer": "falsch", "explanation": "Das wäre die Billigstrategie, Übervorteilung heißt hohe Preise bei tiefer Qualität."},
    {"question": "1.2 c) Die Tasty Dürüm AG verkauft im Januar 1000 Stück zu CHF 10 und im Februar 1500 Stück zu CHF 8. Die daraus abgeleitete Preisabsatzfunktion ist p(x) = 14 - x/250.", "answer": "richtig", "explanation": "Einsetzen der Werte in p(x) = a - b*x bestätigt die Funktion."},
    {"question": "1.2 d) Sie nehmen obige Preisabsatzfunktion und berechnen, dass bei einem Preis von CHF 12 die abgesetzte Menge 600 Stück betragen würde. Zudem identifizieren Sie die Sättigungsmenge bei 3'500 Stück und den Prohibitionspreis bei CHF 14.", "answer": "falsch", "explanation": "Einsetzen ergibt 500 Stück bei CHF 12, also ist die Aussage falsch."},
    {"question": "1.3 a) Leistungen werden grundsätzlich nach intangibel und tangibel unterschieden.", "answer": "richtig", "explanation": "Intangibel = immateriell, tangibel = materiell – das ist korrekt."},
    {"question": "1.3 b) Die 'soziale Anerkennung' durch den Kauf eines auffälligen Sportwagens entspricht dem Erbauungsnutzen.", "answer": "richtig", "explanation": "Soziale Wirkung gehört zum Erbauungsnutzen."},
    {"question": "1.3 c) Mit Maßnahmen im Rahmen der Leistungspflege soll unter anderem die Wachstums- bzw. Reifephase einer Leistung in dessen Lebenszyklus verlängert werden.", "answer": "richtig", "explanation": "Das Ziel der Leistungspflege ist die Verlängerung des Lebenszyklus."},
    {"question": "1.3 d) Bei der Leistungsvariation werden bereits im Markt eingeführte Leistungen durch eine Variante ersetzt, bei der bestimmte Eigenschaften oder Leistungsmerkmale verbessert wurden.", "answer": "richtig", "explanation": "Das ist die Definition der Leistungsvariation."},
    {"question": "1.4 a) Diversifikation eines Produktportfolios kann horizontal, vertikal oder lateral erfolgen.", "answer": "richtig", "explanation": "Das sind die anerkannten Diversifikationsformen."},
    {"question": "1.4 b) Das Anbieten von Jogurts in verschiedenen Geschmacksrichtungen entspricht dem Konzept einer Produktdifferenzierung.", "answer": "richtig", "explanation": "Produktdifferenzierung über Varianten ist hier gegeben."},
    {"question": "1.4 c) (Mass-)Customization ist ein Spezialfall der Produktdifferenzierung und erfüllt individuelle Kundenbedürfnisse mittels einer eigenen Variante.", "answer": "richtig", "explanation": "Mass Customization ist individualisierte Differenzierung."},
    {"question": "1.4 d) Eine Innovation setzt sich schneller durch, wenn ihre Nutzung einfach dargestellt und anderen mitgeteilt werden kann, z.B. mittels Sozialer Medien.", "answer": "richtig", "explanation": "Kommunizierbarkeit ist ein Faktor für die Diffusionsgeschwindigkeit."},
    {"question": "1.5 a) In der Reifephase des Produktlebenszyklus wird der Wettbewerb schwächer und immer mehr neue Konkurrenten treten in den Markt ein.", "answer": "falsch", "explanation": "In der Reifephase nimmt der Wettbewerb zu, neue Anbieter meist früher."},
    {"question": "1.5 b) Der Relaunch ist ein Spezialfall der Leistungsdifferenzierung.", "answer": "richtig", "explanation": "Ein Relaunch stellt eine Differenzierung bestehender Leistungen dar."},
    {"question": "1.5 c) Ein Handelsunternehmen entscheidet sich, anstatt Produkte einzukaufen, diese selbst herzustellen. Das ist eine Form der Diversifikation und nennt sich vertikale Vorwärtsintegration.", "answer": "richtig", "explanation": "Produktion ist vorgelagerte Stufe – vertikale Integration."},
    {"question": "1.5 d) Der generische Innovationsprozess wird in folgende Phasen unterteilt: Ideenphase, Leistungsentwicklung, Markteinführung.", "answer": "richtig", "explanation": "Das sind die klassischen Innovationsphasen."},
    {"question": "1.6 a) Preisnachlässe für Senioren sind eine Form der demografischen Preisdifferenzierung.", "answer": "richtig", "explanation": "Alter als demografisches Merkmal ist Basis der Differenzierung."},
    {"question": "1.6 b) Ziel der Preisdifferenzierung ist es, unterschiedliche Zahlungsbereitschaften abzuschöpfen, um so den Gewinn gegenüber der Einheitspreissetzung zu steigern.", "answer": "richtig", "explanation": "Genau das ist der Zweck der Preisdifferenzierung."},
    {"question": "1.6 c) Man kann durch eine Preiserhöhung keinen Umsatz verlieren.", "answer": "falsch", "explanation": "Eine Preiserhöhung kann Nachfrage reduzieren."},
    {"question": "1.6 d) Die Penetrationsstrategie zielt darauf ab, mit einem tiefen Preis bei der Markteinführung möglichst viel der Zahlungsbereitschaft der Konsument:innen abzuschöpfen.", "answer": "falsch", "explanation": "Penetration will Marktanteile, nicht Zahlungsbereitschaft abschöpfen."},
    {"question": "1.7 a) Die Service Profit Chain zeigt die Wirkung zufriedener Kund:innen auf die Zufriedenheit der Investoren.", "answer": "falsch", "explanation": "Die Kette läuft: Mitarbeiter → Kunden → Profitabilität."},
    {"question": "1.7 b) 'Customer Managed Relationship' bezeichnet den Ansatz, gemäß dem Kund:innen die Beziehung zu Unternehmen selbst bestimmen.", "answer": "richtig", "explanation": "CMR bedeutet kundengetriebene Beziehungsführung."},
    {"question": "1.7 c) 'Cross-Selling' bezeichnet den Verkauf eines Upgrades einer Leistung. 'Up-Selling' hingegen der Verkauf einer zusätzlichen, dazugehörigen Leistung.", "answer": "falsch", "explanation": "Definitionen sind vertauscht: Cross-Selling = Zusatzleistung."},
    {"question": "1.7 d) 'Gebundenheit' bezeichnet die faktische Kundschaftsbindung, welche z.B. durch Verträge erzwungen werden kann. 'Verbundenheit' hingegen bezeichnet die emotionale Kundschaftsbindung.", "answer": "richtig", "explanation": "Die Begriffe sind korrekt definiert."},
    {"question": "1.8 a) 'Fait accompli' im Kündigungsmanagement bedeutet, dass ein Unternehmen eine Kundschaftsbeziehung 'versanden' lässt und z.B. keine Newsletter mehr versendet.", "answer": "richtig", "explanation": "Das beschreibt passives Auslaufenlassen."},
    {"question": "1.8 b) Das Beschwerdeparadoxon beschreibt, dass Kunden bei einer Reklamation, die positiv bearbeitet wurde, hinterher zufriedener sind als Kunden, die nichts zu beanstanden hatten.", "answer": "richtig", "explanation": "Das ist das bekannte Beschwerdeparadoxon."},
    {"question": "1.8 c) Der Inbound-Marketing-Ansatz umfasst vor allem Printwerbung, Direct Mailings, Call Center und TV-Werbung.", "answer": "falsch", "explanation": "Das sind Outbound-Maßnahmen."},
    {"question": "1.8 d) Die Kundenwertanalyse gibt Auskunft über die wertvollsten Kunden aus Unternehmenssicht, und darauf aufbauend werden die Strategien zu ihrer Rückgewinnung gebildet.", "answer": "richtig", "explanation": "Kundenwertanalyse dient Segmentierung und Rückgewinnung."},
    {"question": "1.9 a) Mit der Unique Communications Proposition (UCP) soll analog zur Einzigartigkeit einer Leistung (USP) auch die Kommunikation einzigartig sein.", "answer": "richtig", "explanation": "UCP spiegelt USP in der Kommunikation."},
    {"question": "1.9 b) Kommunikationsziele werden in kognitiv, affektiv und subjektiv unterteilt.", "answer": "falsch", "explanation": "Korrekt ist: kognitiv, affektiv, konativ."},
    {"question": "1.9 c) Die Grundidee von integrierter Kommunikation ist, dass verschiedene Kommunikationsmaßnahmen aufeinander abgestimmt sein sollten, um eine maximale Wirkung zu entfalten.", "answer": "richtig", "explanation": "Das ist das Ziel der integrierten Kommunikation."},
    {"question": "1.9 d) Die Integration von Kommunikationsmaßnahmen kann entweder inhaltlich, formal oder zeitlich erfolgen.", "answer": "falsch", "explanation": "Integration sollte in allen drei Dimensionen erfolgen."},
    {"question": "1.10 a) Mediawerbung ist eine Form der persönlichen Kommunikation.", "answer": "falsch", "explanation": "Mediawerbung ist unpersönlich."},
    {"question": "1.10 b) Public Relations hat zum Ziel die Beziehung zwischen Unternehmen und ausgewählten internen und externen Zielgruppen zu gestalten.", "answer": "richtig", "explanation": "PR zielt auf Beziehungsmanagement."},
    {"question": "1.10 c) Mit Sponsoring fördern Unternehmen Personen und/oder Organisationen in Bereichen wie Sport, Kultur oder Umwelt, um Kommunikationsziele zu erreichen.", "answer": "richtig", "explanation": "Sponsoring ist zielgerichtete Unterstützung."},
    {"question": "1.10 d) Eventmarketing beschreibt ein Kommunikationsinstrument, das der erlebnisorientierten Umsetzung von Marketingzielen durch Events dient.", "answer": "richtig", "explanation": "Das ist die Definition von Eventmarketing."},
    {"question": "1.11 a) Im Block 'Schlüsselaktivitäten' sollten die Gründerinnen die physischen, intellektuellen und menschlichen Ressourcen eintragen, die ihr Unternehmen benötigt.", "answer": "falsch", "explanation": "Ressourcen gehören in den Block 'Schlüsselressourcen', nicht 'Schlüsselaktivitäten'."},
    {"question": "1.11 b) Mit der 'Value Proposition' müssen die Gründerinnen beschreiben, welche Probleme ihrer Kund:innen gelöst werden und welche Bedürfnisse ihre Produkte befriedigen.", "answer": "richtig", "explanation": "Das entspricht der Definition der Value Proposition."},
    {"question": "1.11 c) Im Block 'Wettbewerber', sollten die Gründerinnen, die am Markt bereits bestehenden Konkurrenten analysieren.", "answer": "falsch", "explanation": "Es gibt keinen Block 'Wettbewerber' im Business Model Canvas."},
    {"question": "1.11 d) Bei der Erarbeitung der 'Zielgruppen', müssen die Gründerinnen definieren welche Produkte ihr Unternehmen anbieten will.", "answer": "falsch", "explanation": "Im Block 'Kundensegmente' geht es um die Zielgruppen, nicht um Produkte."},
    {"question": "1.12 a) 'Vertriebskanäle' im Business Model Canvas beschreiben, wie ein Unternehmen mit seinen Kund:innen in Kontakt tritt und ihr Produkt ausliefert.", "answer": "richtig", "explanation": "Das ist die korrekte Funktion der Kanäle im Canvas."},
    {"question": "1.12 b) Der Block 'Kostenstruktur' im Business Model Canvas beschreibt die wichtigsten Kosten und Umsatzquellen eines Unternehmens.", "answer": "falsch", "explanation": "Der Block beschreibt nur die Kostenstruktur, nicht Umsatzquellen."},
    {"question": "1.12 c) Partner sind nicht Teil des Geschäftsmodells und werden im Business Model Canvas darum nicht abgebildet.", "answer": "falsch", "explanation": "Partner werden im Block 'Schlüsselpartner' explizit berücksichtigt."},
    {"question": "1.12 d) Mit den Erlösquellen beschreibt das Unternehmen die Wege, durch die Einnahmen generiert werden.", "answer": "richtig", "explanation": "Das ist die Definition von 'Revenue Streams'."},
    {"question": "1.13 a) Das Five Forces Modell wurde entwickelt, um die interne Wettbewerbsfähigkeit eines Unternehmens zu bewerten.", "answer": "falsch", "explanation": "Es analysiert die externe Branchenstruktur, nicht interne Stärken."},
    {"question": "1.13 b) Im Rahmen der Five Forces Analyse wird die Verhandlungsmacht der Lieferanten untersucht.", "answer": "richtig", "explanation": "Lieferantenmacht ist eine der fünf Kräfte."},
    {"question": "1.13 c) Das Five Forces Modell ist gut dazu geeignet den direkten Einfluss neuer Technologien auf das Unternehmen zu beurteilen.", "answer": "falsch", "explanation": "Technologien werden im Modell nicht direkt betrachtet."},
    {"question": "1.13 d) Wird im Rahmen der Five Forces Analyse eine hohe Bedrohung durch neue Anbieter ersichtlich, kann dies die künftige Rentabilität einer Branche verringern.", "answer": "richtig", "explanation": "Neue Anbieter erhöhen den Wettbewerb und drücken die Rentabilität."},
    {"question": "1.14 a) Im Rahmen der Analyse ist die Bedrohung durch Ersatzprodukte, die von direkten Konkurrenten in der Branche hergestellt werden, ein wesentlicher Faktor.", "answer": "falsch", "explanation": "Ersatzprodukte stammen gerade nicht von direkten Wettbewerbern."},
    {"question": "1.14 b) Die MechTech hat zwei Abnehmer, wobei einer der Abnehmer 90% des Umsatzes ausmacht. Dies reduziert das Geschäftsrisiko für die MechTech, weil ein grosser Teil des Absatzes stets gesichert ist.", "answer": "falsch", "explanation": "Hohe Abhängigkeit von einem Kunden erhöht das Risiko."},
    {"question": "1.14 c) Im Rahmen einer umfassenden Analyse nach Porters Five Forces, sollte die MechTech ökologische und gesellschaftliche Faktoren näher untersuchen.", "answer": "falsch", "explanation": "Diese Faktoren gehören nicht zu den klassischen Five Forces."},
    {"question": "1.14 d) Da die MechTech stark spezialisiert ist und kaum direkte Konkurrenten hat, kann sie die Preise für ihre Produkte freier gestalten als in einem Umfeld mit stärkerer Konkurrenz.", "answer": "richtig", "explanation": "Weniger Konkurrenz bedeutet mehr Preissetzungsspielraum."},
    {"question": "1.15 a) Innerhalb eines Marktsegments sollten die Kund:innen möglichst heterogen sein.", "answer": "falsch", "explanation": "Ein Segment sollte möglichst homogen sein."},
    {"question": "1.15 b) Die Wichtigkeit von Holz-Herkunfts-Siegeln erfüllt für WohnKunst die Anforderung an ein verhaltensrelevantes Segmentierungskriterium.", "answer": "richtig", "explanation": "Das ist ein verhaltensbezogenes Kriterium."},
    {"question": "1.15 c) Die WohnKunst sollte sicherstellen, dass das Potenzial der einzelnen Marktsegmente messbar und quantifizierbar ist.", "answer": "richtig", "explanation": "Messbarkeit ist ein zentrales Kriterium der Segmentierung."},
    {"question": "1.15 d) Um eine gewisse Dynamik zu erhalten ist es sinnvoll, dass sich die Marktsegmente mittel- bis langfristig verändern.", "answer": "falsch", "explanation": "Segmente sollten stabil, nicht dynamisch sein."},
    {"question": "1.16 a) SEO und SEA sind konkurrierende Instrumente und sollten nicht gemeinsam in einer digitalen Marketingstrategie verwendet werden.", "answer": "falsch", "explanation": "Sie können sich sinnvoll ergänzen."},
    {"question": "1.16 b) Im Rahmen der SEA kann die Lesewelt bestimmen für welche Keywords sie Anzeigen schalten möchten.", "answer": "richtig", "explanation": "Keyword-Steuerung ist zentrales Element von SEA."},
    {"question": "1.16 c) Wenn die Lesewelt ihre Webseite in Bezug auf SEO optimiert hat, sind die Effekte sofort sichtbar, sobald Änderungen an der Webseite vorgenommen wurden.", "answer": "falsch", "explanation": "SEO zeigt Effekte oft erst verzögert."},
    {"question": "1.16 d) Die SEA-Strategie hat keinen Einfluss auf die organischen Suchergebnisse für die Lesewelt.", "answer": "richtig", "explanation": "Bezahlte Werbung beeinflusst keine organischen Rankings."},
    {"question": "1.17 a) Die 'Click-Through-Rate (CTR)' zeigt Julia die Anzahl der Benutzer, die auf eine Werbung klicken im Vergleich zur Anzahl der totalen Impressionen einer digitalen Anzeige.", "answer": "richtig", "explanation": "Das ist die Definition der CTR."},
    {"question": "1.17 b) Mit den 'Customer Acquisition Costs (CAC)' beschreibt Julia die Kosten, die anfallen, um eine neue Kund:in zu gewinnen.", "answer": "richtig", "explanation": "CAC misst genau diese Kosten."},
    {"question": "1.17 c) Die 'Conversion Rate' beschreibt die absolute Anzahl der Kunden, die eine bestimmte Aktion vollzogen haben (z.B. ein Produkt kaufen).", "answer": "falsch", "explanation": "Die Conversion Rate ist ein prozentualer Anteil, keine absolute Zahl."},
    {"question": "1.17 d) Anhand der 'Bounce Rate' sieht Julia an, welcher Prozentsatz der Besucher mindestens zwei Seiten der Website von Market Maker besucht haben, bevor sie die Seite wieder verlassen haben.", "answer": "falsch", "explanation": "Bounce Rate misst Besucher, die nur eine Seite ansehen."},
    {"question": "1.18 a) Der 'Customer Lifetime Value (CLV)' misst den Gesamtwert einer Kund:in über den Zeitraum von einem Jahr.", "answer": "falsch", "explanation": "CLV misst den gesamten Wert über die Kundenlebenszeit, nicht nur ein Jahr."},
    {"question": "1.18 b) Mit dem 'Net Promoter Score (NPS)' misst die Fit3 die Effizienz seiner Online-Werbung.", "answer": "falsch", "explanation": "Der NPS misst die Weiterempfehlungsbereitschaft, nicht Werbewirkung."},
    {"question": "1.18 c) Anhand der 'Churn Rate' kann bestimmt werden, wie viele neue Kund:innen in einem bestimmten Zeitraum gewonnen wurden.", "answer": "falsch", "explanation": "Die Churn Rate misst Kundenverluste, nicht -gewinne."},
    {"question": "1.18 d) 'Organic Reach' in den sozialen Medien bezieht sich auf den Effekt der bezahlten Werbeimpressionen die Fit3 erzielt hat.", "answer": "falsch", "explanation": "Organic Reach ist unbezahlte Reichweite."},
    {"question": "1.19 a) Aktive Marketingautomatisierung bezieht sich auf Systeme, die automatisch auf das Verhalten der Nutzer reagieren, wie z.B. das Senden einer E-Mail nach einem Kauf.", "answer": "richtig", "explanation": "Das ist die Definition aktiver Automatisierung."},
    {"question": "1.19 b) Passive Marketingautomatisierung bedeutet, dass ein System regelmäßig Marketingaufgaben ohne menschliches Eingreifen ausführt, unabhängig vom Verhalten der Benutzer.", "answer": "richtig", "explanation": "Das entspricht passiver Automatisierung."},
    {"question": "1.19 c) Bei aktiver Marketingautomatisierung werden Marketingmaßnahmen nur manuell durchgeführt.", "answer": "falsch", "explanation": "Aktive Automatisierung heißt automatische Reaktion auf Nutzungsverhalten."},
    {"question": "1.19 d) Passive Marketingautomatisierung kann beinhalten, regelmäßig Berichte und Analysen zu generieren und an das Marketingteam zu senden.", "answer": "richtig", "explanation": "Das ist ein typisches Beispiel für passive Automatisierung."},
    
    {"question": "2.1 Der Telekom-Anbieter Ollay möchte die Preise seiner Leistungen anpassen. a) Der Internet-Router von Ollay kostet im Einkauf CHF 10 / Stück [...] Das nennt sich kundenorientierte Preissetzung.", "answer": "falsch", "explanation": "Das ist eine kostenorientierte, nicht kundenorientierte Preissetzung."},
    {"question": "2.1 Der Telekom-Anbieter Ollay möchte die Preise seiner Leistungen anpassen. b) Das Handy-Abo Ollay Super One wird [...] Dabei handelt es sich um eine Skimmingstrategie.", "answer": "richtig", "explanation": "Skimmingstrategie = hoher Startpreis, später sinkend – das passt."},
    {"question": "2.1 Der Telekom-Anbieter Ollay möchte die Preise seiner Leistungen anpassen. c) Das Internet-Angebot Ollay Fast Glass wird [...] Dabei handelt es sich um eine technologische Preisdifferenzierung.", "answer": "richtig", "explanation": "Technologische Preisdifferenzierung liegt vor (Gerätetyp abhängig)."},
    {"question": "2.1 Der Telekom-Anbieter Ollay möchte die Preise seiner Leistungen anpassen. d) Das Internet-Angebot Ollay Rather Slow [...] Dabei handelt es sich um eine personelle Preisdifferenzierung.", "answer": "richtig", "explanation": "Studentenrabatt = personelle Preisdifferenzierung."},
    {"question": "2.1 Der Telekom-Anbieter Ollay möchte die Preise seiner Leistungen anpassen. e) Das Internet-Angebot Ollay Friggin’ Fast [...] Dabei handelt es sich um ein gemischtes Preisbündel.", "answer": "richtig", "explanation": "Kombiangebot ist gemischtes Preisbündel."},

    {"question": "2.2 Der internationale Nahrungsmittelkonzern Éltsen AG hat sich entschieden, das Produktportfolio zu überarbeiten. a) Das Produkt Éltcafé soll neu auch noch mit Haselnussgeschmack angeboten werden [...] Produktvarietät.", "answer": "richtig", "explanation": "Unterschied im Geschmack = Produktvarietät."},
    {"question": "2.2 Der internationale Nahrungsmittelkonzern Éltsen AG hat sich entschieden, das Produktportfolio zu überarbeiten. b) Das Produkt Éltcafé soll neu auch ohne Koffein angeboten werden [...] Produktvarietät.", "answer": "richtig", "explanation": "Koffeinfrei = andere Variante = Produktvarietät."},
    {"question": "2.2 Der internationale Nahrungsmittelkonzern Éltsen AG hat sich entschieden, das Produktportfolio zu überarbeiten. c) Das Produkt Éltcafé enthält [...] Diese werden nun ersetzt. [...] Leistungsvariation.", "answer": "richtig", "explanation": "Rezepturänderung = Leistungsvariation."},
    {"question": "2.2 Der internationale Nahrungsmittelkonzern Éltsen AG hat sich entschieden, das Produktportfolio zu überarbeiten. d) Das Produkt Éltcafé erhält neue Verpackung [...] Produkt-Relaunch.", "answer": "richtig", "explanation": "Verpackung + Preisänderung = Relaunch."},
    {"question": "2.2 Der internationale Nahrungsmittelkonzern Éltsen AG hat sich entschieden, das Produktportfolio zu überarbeiten. e) Éltsen druckt Rezeptideen auf Verpackung [...] Value-Added-Service.", "answer": "richtig", "explanation": "Zusätzlicher Service = Value-Added."},

    {"question": "2.3 Die Versicherung Railibom möchte sein Kundenmanagement neu aufsetzen. a) Zukünftig soll mehr nach dem Paradigma des Inbound-Marketings gearbeitet werden.", "answer": "richtig", "explanation": "Inbound = Content Marketing, weniger Push wie Direct Mail."},
    {"question": "2.3 Die Versicherung Railibom möchte sein Kundenmanagement neu aufsetzen. b) Im Rahmen einer Kundenwert-Analyse wurden A-, B-, C-Kunden segmentiert.", "answer": "richtig", "explanation": "Typische ABC-Segmentierung zur Ressourcenallokation."},
    {"question": "2.3 Die Versicherung Railibom möchte sein Kundenmanagement neu aufsetzen. c) Neukunden sollen mit 24-Monats-Vertrag gebunden werden. [...] Verbundenheitsstrategie.", "answer": "falsch", "explanation": "Das ist Gebundenheit, nicht emotionale Verbundenheit."},
    {"question": "2.3 Die Versicherung Railibom möchte sein Kundenmanagement neu aufsetzen. d) Unattraktive Kunden zahlen höhere Prämien bis Kündigung. [...] Cost Escalation.", "answer": "richtig", "explanation": "Cost Escalation trifft hier zu."},
    {"question": "2.3 Die Versicherung Railibom möchte sein Kundenmanagement neu aufsetzen. e) Jeder Kunde erhält Kundenwertanalyse zur Investitionsplanung.", "answer": "richtig", "explanation": "Kundenwertanalyse für Steuerung und Bindung sinnvoll."},

    {"question": "2.4 Das Handelsunternehmen Pooc überarbeitet seine Kommunikationsstrategie. a) Vegane Kund:innen über Inhaltsstoffe informieren. [...] kognitives Kommunikationsziel.", "answer": "richtig", "explanation": "Faktenwissen = kognitives Ziel."},
    {"question": "2.4 Das Handelsunternehmen Pooc überarbeitet seine Kommunikationsstrategie. b) Einheitliche Logos, Farben etc. [...] formale Integration.", "answer": "richtig", "explanation": "Standard-Beispiel für formale Integration."},
    {"question": "2.4 Das Handelsunternehmen Pooc überarbeitet seine Kommunikationsstrategie. c) Für einzigartige Leistung auch USP entwickeln.", "answer": "falsch", "explanation": "Für Kommunikation = UCP, nicht USP."},
    {"question": "2.4 Das Handelsunternehmen Pooc überarbeitet seine Kommunikationsstrategie. d) Sponsoring bringt laut Marketingverantwortlichen keine Vorteile.", "answer": "richtig", "explanation": "Sponsoring kann auch Risiken bergen – korrekt formuliert."},
    {"question": "2.4 Das Handelsunternehmen Pooc überarbeitet seine Kommunikationsstrategie. e) Pooc zahlt für Einblendung in TV-Serie – Product Placement.", "answer": "richtig", "explanation": "Typisches Beispiel für Product Placement."},

    {"question": "2.5 Die mittelständische Böller AG möchte ihr Produktangebot diversifizieren. In welchem Zusammenhang würde die PESTEL-Analyse am sinnvollsten angewendet? a) Auswahl von Lieferanten für neue Produktkomponenten.", "answer": "falsch", "explanation": "Lieferantenwahl ist mikroökonomisch, nicht PESTEL-relevant."},
    {"question": "2.5 Die mittelständische Böller AG möchte ihr Produktangebot diversifizieren. In welchem Zusammenhang würde die PESTEL-Analyse am sinnvollsten angewendet? b) Entwicklung neuer Technologien für die Produktion.", "answer": "falsch", "explanation": "Technologieentwicklung ist intern – nicht externes Umfeld."},
    {"question": "2.5 Die mittelständische Böller AG möchte ihr Produktangebot diversifizieren. In welchem Zusammenhang würde die PESTEL-Analyse am sinnvollsten angewendet? c) Einschätzung des Marktwachstums und neuer Kundensegmente.", "answer": "richtig", "explanation": "Demografisch/sozio-kulturell – PESTEL-relevant."},
    {"question": "2.5 Die mittelständische Böller AG möchte ihr Produktangebot diversifizieren. In welchem Zusammenhang würde die PESTEL-Analyse am sinnvollsten angewendet? d) Verständnis des makroökonomischen Umfelds.", "answer": "richtig", "explanation": "Makroökonomische Trends = zentrales Element der PESTEL."},
    {"question": "2.5 Die mittelständische Böller AG möchte ihr Produktangebot diversifizieren. In welchem Zusammenhang würde die PESTEL-Analyse am sinnvollsten angewendet? e) Entwurf von Produktdesigns, die auf Verbrauchervorlieben abzielen.", "answer": "falsch", "explanation": "Designentwicklung ist intern, nicht Umfeldfaktor."},

    {"question": "2.6 Das Softwareunternehmen SAN-IT-AS erwägt die Entwicklung eines neuen Produktes für den Gesundheitssektor. In welcher Phase des Entscheidungsprozesses würde eine PESTEL-Analyse den grössten Nutzen bieten? a) Festlegung des anfänglichen Feature-Sets für das Produkt.", "answer": "falsch", "explanation": "Feature-Set ist internes Design, kein Umfeldbezug."},
    {"question": "2.6 Das Softwareunternehmen SAN-IT-AS erwägt die Entwicklung eines neuen Produktes für den Gesundheitssektor. In welcher Phase des Entscheidungsprozesses würde eine PESTEL-Analyse den grössten Nutzen bieten? b) Analyse des externen Umfelds zur Sicherstellung der langfristigen Tragfähigkeit.", "answer": "richtig", "explanation": "Genau dafür ist die PESTEL-Analyse gedacht."},
    {"question": "2.6 Das Softwareunternehmen SAN-IT-AS erwägt die Entwicklung eines neuen Produktes für den Gesundheitssektor. In welcher Phase des Entscheidungsprozesses würde eine PESTEL-Analyse den grössten Nutzen bieten? c) Programmierung und technischer Entwurf der Software.", "answer": "falsch", "explanation": "Programmierung = technische Umsetzung, kein PESTEL-Zeitpunkt."},
    {"question": "2.6 Das Softwareunternehmen SAN-IT-AS erwägt die Entwicklung eines neuen Produktes für den Gesundheitssektor. In welcher Phase des Entscheidungsprozesses würde eine PESTEL-Analyse den grössten Nutzen bieten? d) Bewertung des Wettbewerbsumfelds im Gesundheitssektor.", "answer": "falsch", "explanation": "Wettbewerb = Teil von Porter's Five Forces, nicht PESTEL."},
    {"question": "2.6 Das Softwareunternehmen SAN-IT-AS erwägt die Entwicklung eines neuen Produktes für den Gesundheitssektor. In welcher Phase des Entscheidungsprozesses würde eine PESTEL-Analyse den grössten Nutzen bieten? e) Entscheidung über das Budget für die Produktmarketing-Kampagne.", "answer": "falsch", "explanation": "Budgetierung ist interne Finanzplanung, kein PESTEL-Thema."},

    {"question": "1.1 a) Das Pricing ist von untergeordneter Bedeutung im Marketing-Mix, weil es lediglich einen indirekten Einfluss auf die Unternehmenskennzahlen hat.", "answer": "falsch", "explanation": "Pricing hat direkten Einfluss auf Umsatz und Gewinn, nicht nur indirekt."},
{"question": "1.1 b) Der Prestigeeffekt des Preises beschreibt eine steigende Absatzmenge nach einer Preiserhöhung.", "answer": "richtig", "explanation": "Beim Prestigeeffekt wird durch höhere Preise ein höherer Wert suggeriert, was die Nachfrage steigern kann."},
{"question": "1.1 c) Der Preisankereffekt beschreibt, dass Kunden den Preis eines Komplementärgutes herbeiziehen, um einen Preis im Rahmen einer Kaufentscheidung einzustufen.", "answer": "falsch", "explanation": "Beim Preisankereffekt wird ein Referenzpreis gesetzt, aber nicht durch Komplementärprodukte."},
{"question": "1.1 d) Ein OLED-Fernseher kostet CHF 1200, die variablen Produktionskosten entsprechen CHF 600 pro Stück und die Fixkosten CHF 300'000. Von den Fernsehern verkaufen Sie 1'000 Stück. Der resultierende Gewinn beträgt CHF 300'000.", "answer": "falsch", "explanation": "Gewinn = 1000 * (1200 - 600) - 300000 = CHF 300'000, stimmt nur bedingt – es handelt sich eher um den Deckungsbeitrag."},
{"question": "1.2 a) Der Preis ist der effektivste Gewinn­treiber. D. h. eine 10%-ige Verbesserung (Erhöhung) des Preises erhöht den Gewinn am stärksten verglichen mit den variablen Kosten pro Einheit, der Absatzmenge und den Fixkosten.", "answer": "richtig", "explanation": "Preiserhöhungen wirken sich überproportional auf den Gewinn aus."},
{"question": "1.2 b) Kundenorientierte Preissetzung (im Kontext des Magischen Dreiecks des Pricings) bedeutet, dass man die Preise gemäss der Zahlungsbereitschaft der Kunden setzt.", "answer": "richtig", "explanation": "Kundenorientierung heißt, den Preis an der Zahlungsbereitschaft auszurichten."},
{"question": "1.2 c) Im Rahmen der Preispositionierung wird eine hohe Qualität zu tiefen Preisen als Vorteilsstrategie bezeichnet.", "answer": "falsch", "explanation": "Das wäre die Tiefpreisstrategie; eine hohe Qualität zu tiefem Preis ist unrealistisch."},
{"question": "1.2 d) Bei der Skimmingstrategie ist der Preis bei der Produkteinführung hoch und wird dann über die Zeit reduziert.", "answer": "richtig", "explanation": "Skimming nutzt Zahlungsbereitschaft zu Beginn und senkt dann den Preis."},
{"question": "1.3 a) Der Autohersteller TAIF verkauft seine Fahrzeuge an Kunden in den USA zu einem höheren Preis als in Europa. Das wird als «personelle Preisdifferenzierung» bezeichnet.", "answer": "falsch", "explanation": "Das ist eine geografische (regionale) Preisdifferenzierung, nicht personell."},
{"question": "1.3 b) Im Kontext von Preisbündelung spricht man von «gemischten» Preisbündeln, wenn die Leistungskomponenten auch einzeln erhältlich sind, von «reinen» Preisbündeln, wenn die Leistungskomponenten nicht einzeln erhältlich sind.", "answer": "richtig", "explanation": "Die Definitionen von gemischtem und reinem Bündel stimmen."},
{"question": "1.3 c) Der Elektronikkonzern Sungsam verkauft im Januar 2024 1000 Smartphones zu CHF 900 pro Stück und nach einer Preissenkung im Februar 1200 Stück zu CHF 800. Die daraus abgeleitete Preisabsatzfunktion ist p(x) = 1400 - (1/2)x", "answer": "richtig", "explanation": "Lineare Ableitung ist korrekt: zwei Punkte (1000/900) und (1200/800) liefern diese Funktion."},
{"question": "1.3 d) Sie nehmen obige Preisabsatzfunktion und berechnen, dass bei einem Preis von CHF 600 die abgesetzte Menge 1600 Stück betragen würde. Zudem identifizieren Sie die Sättigungsmenge bei 2800 Stück und den Prohibitionspreis bei CHF 1400.", "answer": "richtig", "explanation": "p(x) = 1400 - 0.5x → x=1600 bei p=600, x=2800 bei p=0, p=1400 bei x=0 – alles korrekt."},
{"question": "1.4 a) Das Stage-Gate-Modell ist Innovationsmodell spezifisch für intangible Leistungen.", "answer": "falsch", "explanation": "Das Stage-Gate-Modell gilt allgemein, nicht nur für Dienstleistungen."},
{"question": "1.4 b) Scrum eignet sich vor allem für die Entwicklung von Leistungen mit tiefer Komplexität im Dienstleistungsbereich.", "answer": "falsch", "explanation": "Scrum ist gerade für komplexe Entwicklungsprojekte geeignet, nicht für einfache."},
{"question": "1.4 c) Ein langsames Wachstum des Absatzes/Umsatzes/Gewinns ist ein Indikator, dass sich ein Produkt in der Schrumpfungsphase im Produktlebenszyklus befindet.", "answer": "falsch", "explanation": "Schrumpfung ist durch Rückgang, nicht langsames Wachstum gekennzeichnet."},
{"question": "1.4 d) In der Reifephase beschäftigt sich das Marketing hauptsächlich mit der Leistungspflege, um Gewinne zu maximieren bzw. Marktanteile zu sichern.", "answer": "richtig", "explanation": "Leistungspflege ist typisch für die Reifephase, um Marktanteile zu sichern."},
{"question": "1.5 a) Diversifikation eines Produktportfolios kann nur vertikal oder lateral erfolgen.", "answer": "falsch", "explanation": "Diversifikation kann vertikal, horizontal oder lateral erfolgen, daher ist diese Aussage falsch."},
{"question": "1.5 b) Das Anbieten von laktosefreien Jogurts entspricht dem Konzept der Produktdifferenzierung.", "answer": "richtig", "explanation": "Produktdifferenzierung beschreibt Varianten eines Produkts wie Geschmack oder Inhaltsstoffe."},
{"question": "1.5 c) Die SORGIM Bank hat entschieden, Fast Food Restaurants zu eröffnen. Das ist ein Beispiel von einer lateralen Diversifikation.", "answer": "richtig", "explanation": "Laterale Diversifikation liegt vor, wenn das neue Geschäftsfeld keinen direkten Zusammenhang mit dem bisherigen hat."},
{"question": "1.5 d) Der Elektronikkonzern Sungsam wird ab nächstem Jahr eigene Minen betreiben, um Rohstoffe für die Produktion zu gewinnen. Das ist ein Beispiel von vertikaler Diversifikation, genauer «Vorwärtsintegration».", "answer": "falsch", "explanation": "Das ist Rückwärtsintegration, da vorgelagerte Produktionsstufen übernommen werden."},
{"question": "1.6 a) Die Service Profit Chain zeigt die unmittelbare Wirkung zufriedener Kunden auf die Zufriedenheit der Mitarbeiter.", "answer": "falsch", "explanation": "Die Service Profit Chain zeigt, dass zufriedene Mitarbeitende zu zufriedenen Kunden führen, nicht umgekehrt."},
{"question": "1.6 b) «Customer Managed Relationship» bezeichnet den Ansatz, dass Kunden die Beziehung zu Unternehmen bestimmen.", "answer": "richtig", "explanation": "Kunden übernehmen die Kontrolle über Kommunikationskanäle und Interaktion."},
{"question": "1.6 c) «Cross-Selling» bezeichnet den Verkauf einer zusätzlichen, dazugehörigen Leistung, «Up-Selling» hingegen der Verkauf einer höherwertigeren Leistung.", "answer": "falsch", "explanation": "Die Definitionen sind vertauscht: Cross-Selling ist Zusatzverkauf, Up-Selling ist ein höherwertiges Produkt."},
{"question": "1.6 d) «Gebundenheit» bezeichnet die faktische Kundenbindung, welche z.B. durch Verträge erzwungen werden kann. «Verbundenheit» hingegen bezeichnet die emotionale Kundschaftsbindung.", "answer": "richtig", "explanation": "Diese Definitionen sind korrekt."},
{"question": "1.7 a) «Fait accompli» im Kündigungsmanagement bedeutet, dass ein Unternehmen eine Kundschaftsbeziehung «versanden» lässt und z.B. keine Newsletter mehr versendet.", "answer": "richtig", "explanation": "Das beschreibt passives Auslaufenlassen einer Beziehung."},
{"question": "1.7 b) Das Beschwerdeparadoxon beschreibt, dass Kunden bei einer Reklamation, die positiv bearbeitet wurde, hinterher zufriedener sind als Kunden, die nichts zu beanstanden hatten.", "answer": "richtig", "explanation": "Das ist das bekannte Beschwerdeparadoxon."},
{"question": "1.7 c) Der Outbound-Marketing-Ansatz umfasst u.a. Content-Marketing, SEO und Social Media Marketing.", "answer": "falsch", "explanation": "Das sind Inbound-Maßnahmen, Outbound ist z.B. TV, Direct Mail."},
{"question": "1.7 d) Der Onlineshop Intertec sammelt nach Bestellabschluss NPS-Daten, sie haben folgende Angaben: ... Der daraus errechnete NPS beläuft sich auf 20.", "answer": "richtig", "explanation": "NPS = (80-40)/200 * 100 = 20% ist korrekt berechnet."},
{"question": "1.8 a) Das wertorientierte Kundenmanagement verfolgt als zentrales Ziel, den Aufbau von möglichst profitablen Kundenbeziehungen, wobei der Customer Value im Vordergrund steht.", "answer": "richtig", "explanation": "Customer Value ist der zentrale Steuerungsfaktor im wertorientierten Management."},
{"question": "1.8 b) Der Customer Lifetime Value ist in seiner Grundform eine eindimensionale und gegenwartsbezogene Form der Kundenwertberechnung.", "answer": "falsch", "explanation": "CLV ist zukunftsorientiert, nicht gegenwartsbezogen."},
{"question": "1.8 c) Es sei gegeben: E₀ = 1000, K₀ = 500, r = 2 %, ... CLV ≈ 1262", "answer": "richtig", "explanation": "Die Berechnung ist korrekt, ergibt aufgerundet 1262."},
{"question": "1.8 d) Scoring Modelle zur Ermittlung des Customer Values sind relativ starr und erlauben lediglich die Berücksichtigung von qualitativen Kriterien.", "answer": "falsch", "explanation": "Scoring-Modelle erlauben v.a. quantitative Kriterien, qualitative nur begrenzt."},
{"question": "1.9 a) Das SOR-Modell beschreibt den Einfluss des Verhaltens auf die Prozesse in einem Organismus.", "answer": "falsch", "explanation": "Das SOR-Modell beschreibt Reiz-Reaktionsprozesse beim Konsumenten, nicht biologische Organismen."},
{"question": "1.9 b) Die Kenntnis von Marken (Bekanntheitsgrad, Namenskenntnisse) und das Wissen über Produkte sind typische Beispiele von konativen Kommunikationszielen.", "answer": "falsch", "explanation": "Das sind kognitive Ziele, nicht konative, welche auf Verhalten abzielen."},
{"question": "1.9 c) Die Formen der integrierten Kommunikation sind: Inhaltliche Integration, formale Integration und zeitliche Integration.", "answer": "richtig", "explanation": "Das sind die drei zentralen Formen der integrierten Kommunikation."},
{"question": "1.9 d) Bei der formalen Integration geht es u.a. um einheitliche Logos und Schriftarten.", "answer": "richtig", "explanation": "Einheitliches Design ist ein Merkmal der formalen Integration."},
{"question": "1.10 a) Beispiele für Direct Marketing sind u.a. Printanzeigen, Plakate und Kinowerbung.", "answer": "falsch", "explanation": "Das sind klassische Werbeformen, keine direkten (persönlichen) Marketingmaßnahmen."},
{"question": "1.10 b) Public Relations hat vorrangig zum Ziel zusätzliche Verkäufe zu generieren.", "answer": "falsch", "explanation": "PR dient primär der Beziehungspflege, nicht der Verkaufsförderung."},
{"question": "1.10 c) Mit Event Marketing wollen Unternehmen Werbebotschaften in tatsächliche Ereignisse umsetzen und damit Markenwelten erlebbar machen.", "answer": "richtig", "explanation": "Erlebnisorientierte Markeninszenierung ist Ziel des Eventmarketings."},
{"question": "1.10 d) Im Rahmen von Product Placement integrieren Unternehmen ihre Produkte oder ihre Marke in ein anderes Werk und werden für die Bereitstellung der Produkte vergütet.", "answer": "richtig", "explanation": "Product Placement beschreibt genau diese Maßnahme in Medieninhalten."},
{"question": "1.11 a) Im Block «Kundenbeziehungen» soll zum Beispiel beschrieben werden über welche Kanäle der Kundendienst mit den Kunden kommuniziert. Customer Relationship Management und Revenue Planning stehen hier im Vordergrund.", "answer": "richtig", "explanation": "Das ist die richtige Funktion des Blocks «Kundenbeziehungen» im Business Model Canvas."},
{"question": "1.11 b) Ein Vertriebskanal kann sowohl physischer wie auch digitaler Natur sein.", "answer": "richtig", "explanation": "Beide Kanalformen sind korrekt und Teil des Canvas."},
{"question": "1.11 c) Zu den Schlüsselressourcen gehören unter anderem die wichtigsten Partner des Unternehmens.", "answer": "falsch", "explanation": "Partner gehören in den Block «Schlüsselpartner», nicht «Schlüsselressourcen»."},
{"question": "1.11 d) Bei den Schlüsselaktivitäten sollten die wichtigsten Aktivitäten, die ein Unternehmen benötigt, um erfolgreich zu sein beschrieben werden.", "answer": "richtig", "explanation": "Das ist die Definition der Schlüsselaktivitäten im Canvas."},
  {"question": "1.9 a) Das SOR-Modell beschreibt den Einfluss des Verhaltens auf die Prozesse in einem Organismus.", "answer": "falsch", "explanation": "Das SOR-Modell beschreibt Reiz-Verarbeitung-Reaktion im Marketing, nicht biologische Prozesse."},
  {"question": "1.9 b) Die Kenntnis von Marken (Bekanntheitsgrad, Namenskenntnisse) und das Wissen über Produkte sind typische Beispiele von konativen Kommunikationszielen.", "answer": "falsch", "explanation": "Das sind kognitive Ziele. Konative Ziele betreffen Verhalten, z.B. Kaufabsicht."},
  {"question": "1.9 c) Die Formen der integrierten Kommunikation sind: Inhaltliche Integration, formale Integration und zeitliche Integration.", "answer": "richtig", "explanation": "Das sind die drei anerkannten Formen der Integration in der Kommunikation."},
  {"question": "1.9 d) Bei der formalen Integration geht es u. a. um einheitliche Logos und Schriftarten.", "answer": "richtig", "explanation": "Formale Integration betrifft visuelle Gestaltungsmerkmale."},
  {"question": "1.10 a) Beispiele für Direct Marketing sind u. a. Printanzeigen, Plakate und Kinowerbung.", "answer": "falsch", "explanation": "Das sind klassische Medienwerbung, Direct Marketing ist z.B. E-Mail oder personalisierte Post."},
  {"question": "1.10 b) Public Relations hat vorrangig zum Ziel zusätzliche Verkäufe zu generieren.", "answer": "falsch", "explanation": "PR zielt auf Beziehungsaufbau, nicht direkt auf Verkaufssteigerung."},
  {"question": "1.10 c) Mit Event Marketing wollen Unternehmen Werbebotschaften in tatsächliche Ereignisse umsetzen und damit Markenwelten erlebbar machen.", "answer": "richtig", "explanation": "Event Marketing dient der emotionalen Markeninszenierung."},
  {"question": "1.10 d) Im Rahmen von Product Placement integrieren Unternehmen ihre Produkte oder ihre Marke in ein anderes Werk und werden für die Bereitstellung der Produkte vergütet.", "answer": "richtig", "explanation": "Das ist die Definition von Product Placement."},
  {"question": "1.11 a) Im Block 'Kundenbeziehungen' soll z.B. beschrieben werden über welche Kanäle der Kundendienst mit den Kunden kommuniziert. Customer Relationship Management und Revenue Planning stehen hier im Vordergrund.", "answer": "richtig", "explanation": "Diese Inhalte gehören korrekt in den Block 'Kundenbeziehungen' im BMC."},
  {"question": "1.11 b) Ein Vertriebskanal kann sowohl physischer wie auch digitaler Natur sein.", "answer": "richtig", "explanation": "Kanäle im BMC umfassen beide Varianten."},
  {"question": "1.11 c) Zu den Schlüsselressourcen gehören unter anderem die wichtigsten Partner des Unternehmens.", "answer": "falsch", "explanation": "Partner gehören in den Block 'Schlüsselpartner', nicht 'Schlüsselressourcen'."},
  {"question": "1.11 d) Bei den Schlüsselaktivitäten sollten die wichtigsten Aktivitäten, die ein Unternehmen benötigt, um erfolgreich zu sein beschrieben werden.", "answer": "richtig", "explanation": "Das entspricht genau dem Zweck des Blocks 'Schlüsselaktivitäten'."},
  {"question": "1.12 a) Die PESTEL-Analyse ist ein Makroinstrument und fokussiert auf branchenspezifische Eigenheiten.", "answer": "falsch", "explanation": "PESTEL fokussiert auf makroökonomische, nicht branchenspezifische Einflüsse."},
  {"question": "1.12 b) Mit dem Business Model Canvas werden Faktoren beschrieben, die die meisten Unternehmen kaum selbst beeinflussen können.", "answer": "falsch", "explanation": "Im BMC werden unternehmensinterne, beeinflussbare Elemente modelliert."},
  {"question": "1.12 c) Bei den Porter's Five Forces werden unter anderem mögliche Ersatzprodukte evaluiert. Bei deren Beurteilung spielen unter anderem Wechselkosten und Produktloyalität eine Rolle.", "answer": "richtig", "explanation": "Wechselkosten und Loyalität beeinflussen die Bedrohung durch Substitute."},
  {"question": "1.12 d) Aus Sicht des Autoherstellers Mini ist die zunehmende Beliebtheit von elektrischen Fahrzeugen in Europa eine Schwäche, weil Mini diese Entwicklung selbst gut kontrollieren kann.", "answer": "falsch", "explanation": "Diese externe Entwicklung ist eine Bedrohung, nicht kontrollierbare Schwäche."},
  {"question": "1.13 a) Im Value Proposition Canvas wird die Unternehmenssicht (Wertversprechen) 'spiegelbildlich' zu der Kundensicht (Kundenprofil) betrachtet.", "answer": "richtig", "explanation": "Das Canvas besteht genau aus diesen beiden spiegelnden Perspektiven."},
  {"question": "1.13 b) In den Bereich des Wertversprechens fällt die Formulierung von konkreten Kundenaufgaben, die wiederum in die Typen 'funktionell', 'sozial' und 'emotional' unterteilt werden.", "answer": "falsch", "explanation": "Kundenaufgaben gehören zum Kundenprofil, nicht zum Wertversprechen."},
  {"question": "1.13 c) Als Teil des Kundenprofils werden verschiedene Typen von Nutzen und Gewinnen definiert. Dazu gehören sowohl erwartete wie auch unerwartete Vorteile.", "answer": "richtig", "explanation": "Nutzenkategorien sind Teil des Kundenprofils."},
  {"question": "1.13 d) Das Wertversprechen wird auch 'Value Map' genannt. Hier geht es um die Merkmale eines spezifischen Wertangebots für spezifische Kundensegmente.", "answer": "richtig", "explanation": "Die Value Map bildet die Unternehmenssicht mit Produkten, Nutzen, etc."},
  {"question": "1.14 a) System 1 funktioniert schnell, intuitiv und basierend auf Heuristiken.", "answer": "richtig", "explanation": "Das entspricht Kahnemans System-1-Beschreibung."},
  {"question": "1.14 b) Dark Patterns sind technische Interventionen, die nötig sind, um User Interfaces in einem Dark- und Light-Mode anzubieten. Bestimmte User Flows müssen dafür auch auf dunklen Screens funktionieren.", "answer": "falsch", "explanation": "Dark Patterns sind manipulative Designelemente, nicht Design-Themen."},
  {"question": "1.14 c) Wenn wir digitale Produkte designen, sollten wir wo immer möglich verhindern, dass die User sich auf ihre Intuition verlassen. Das ist gefährlich und führt oft zu systematischen Fehlern (Bias).", "answer": "richtig", "explanation": "Verlassen auf Intuition kann kognitive Verzerrungen verstärken."},
  {"question": "1.14 d) Ein Sludge ist eine negative Version eines Nudges (Stupsers). Ein Beispiel dafür ist ein absichtlich komplex gestalteter User Flow, der ein User durchlaufen muss um sich von einem Newsletter abzumelden.", "answer": "richtig", "explanation": "Sludge ist der Begriff für solche 'negative Nudges'."},
  {"question": "1.15 a) Bei User Interviews erklärt man den Usern wie das Produkt funktioniert und erfährt so wie ihr mentales Modell aussieht.", "answer": "richtig", "explanation": "Interviews sind geeignet zur Analyse mentaler Modelle."},
  {"question": "1.15 b) Beim Open Card Sorting können die User beliebige, für sie sinnvolle Gruppen von Karten bilden, die für sie zusammengehören.", "answer": "richtig", "explanation": "Open Card Sorting erlaubt freie Gruppierung, passend zur Analyse mentaler Strukturen."},
  {"question": "1.15 c) A/B Tests sind gut geeignet, um die mentalen Modelle der User für das gesamte Produkt zu erfassen.", "answer": "falsch", "explanation": "A/B-Tests messen Verhalten, nicht direkt mentale Modelle."},
  {"question": "1.15 d) Bei der Task Analysis beobachtet man die User dabei, wie sie bestimmte Aufgaben mit dem bereits fertigen Produkt oder System lösen. So kann man mit der Zeit nachvollziehen, wie ihr mentales Modell des Produkts oder Systems ungefähr aussehen dürfte.", "answer": "richtig", "explanation": "Task Analysis erlaubt Rückschlüsse auf mentale Modelle."},
  {"question": "1.16 a) Das Hook Modell ist ein Ansatz um 'habit-forming Products' zu entwickeln. Eine Voraussetzung um eine Gewohnheit (habit) zu entwickeln ist, dass die Nutzer mindestens einmal pro Monat mit der App interagieren.", "answer": "falsch", "explanation": "Für habit formation ist tägliche oder wöchentliche Nutzung nötig, monatlich ist zu selten."},
  {"question": "1.16 b) Wenn User gelernt haben die App immer in bestimmten, wiederkehrenden Situationen (z.B. wenn sie ins Bett gehen) zu nutzen, hat es Nevolut geschafft einen internen Trigger zu etablieren.", "answer": "richtig", "explanation": "Das ist ein Ziel des Hook-Modells: interner Trigger durch Gewohnheit."},
  {"question": "1.16 c) Bei den variablen Belohnungen (Rewards) unterscheidet Eyal drei Typen. Dazu gehören 'Rewards of the Tribe'. Damit sind materielle Gewinne wie zum Beispiel monetäre Preise gemeint.", "answer": "falsch", "explanation": "Rewards of the Tribe sind soziale Belohnungen, nicht materielle."},
  {"question": "1.16 d) Das Behavior Modell von B.J. Fogg besagt, dass es vier Faktoren braucht, um ein Verhalten auszulösen. Als Produktdesigner kann man mit gutem UI-Design unter anderem die Dimension der Fähigkeit (Ability) wesentlich beeinflussen.", "answer": "richtig", "explanation": "Das Fogg-Modell umfasst Motivation, Fähigkeit, Trigger – Ability ist relevant."},
  {"question": "1.17 a) Ein Unique Visitor ist ein Webseitenbesuchender, der besonders auffällige Merkmale aufweist.", "answer": "falsch", "explanation": "Unique Visitor meint eindeutiger, individueller Besucher, nicht auffälliger."},
  {"question": "1.17 b) Der Net Promoter Score beschreibt die Weiterempfehlungsrate und wird auf einer klassischen Likert Skala mit Werten von 1 bis 7 erfasst.", "answer": "falsch", "explanation": "NPS nutzt eine 11er-Skala (0–10), nicht eine 7er-Skala."},
  {"question": "1.17 c) Die Traffic-Quelle beschreibt über welchen Kanal ein User auf die Webseite gelangt ist (z.B. paid search oder organic search).", "answer": "richtig", "explanation": "Das ist die korrekte Definition der Traffic-Quelle."},
  {"question": "1.17 d) Die Bounce Rate zeigt Marlon den Anteil der User, die direkt nach der Einstiegsseite (Landingpage) die Seite wieder verlassen.", "answer": "richtig", "explanation": "Das entspricht genau der Definition der Bounce Rate."},
  {"question": "1.18 a) Die automatisierte Personalisierung von Marketing-E-Mails (z.B. Newsletter) mit Informationen aus den Profilinformationen eines Users ist ein Beispiel von aktiver Marketing Automation.", "answer": "richtig", "explanation": "Aktive Automatisierung reagiert auf individuelles Verhalten."},
  {"question": "1.18 b) Ein häufig genannter Nutzen von Marketing Automation ist Zeitersparnis bei repetitiven Aufgaben.", "answer": "richtig", "explanation": "Das ist ein Hauptvorteil von Automatisierung im Marketing."},
  {"question": "1.18 c) Bei automatischen Antworten auf Kundenanfragen, die ausgelöst werden, sobald eine Kundin ein Kontaktformularen abgeschickt hat, handelt es sich um aktive Marketing Automation.", "answer": "richtig", "explanation": "Aktive Automatisierung reagiert auf ein direktes Ereignis."},
  {"question": "1.18 d) Wenn Kunden drei Wochen nach einem Kauf dazu angeregt werden, ein Produkt zu bewerten handelt es sich um passive Marketingautomatisierung.", "answer": "falsch", "explanation": "Auch das ist aktive Automation, da es auf einem Trigger basiert."},
{"question": "2.1 Der Telekom-Anbieter Suncom möchte die Preise seiner Leistungen anpassen. a) Suncom hatte ursprünglich 1 tiefpreisigen und 1 mittelpreisigen Router im Angebot, wobei meist der tiefpreisige gekauft wurde. Nachdem noch ein hochpreisiger Premium-Router ins Sortiment aufgenommen wurde, wird nun der mittelpreisige Router am meisten verkauft. Das ist der sog. Kompromisseffekt des Preises.", "answer": "richtig", "explanation": "Der Kompromisseffekt beschreibt genau diesen Effekt – der Mittelwert wird durch einen teureren Anker attraktiver."},
{"question": "2.1 Der Telekom-Anbieter Suncom möchte die Preise seiner Leistungen anpassen. b) Suncom verkauft das neue Smartphone Milkyway 13 Pro. Am Anfang kostet das Phone CHF 600 und wird dann über die Zeit teurer. Das wird als Penetrationsstrategie bezeichnet.", "answer": "falsch", "explanation": "Die Penetrationsstrategie setzt zu Beginn niedrige Preise, die später erhöht werden. Hier geschieht das Gegenteil, also falsch."},
{"question": "2.1 Der Telekom-Anbieter Suncom möchte die Preise seiner Leistungen anpassen. c) Das Internet-Angebot Suncom Glass wird für Studenten vergünstigt angeboten. Das ist eine Form der personellen Preisdifferenzierung.", "answer": "richtig", "explanation": "Personelle Preisdifferenzierung liegt vor, wenn Zielgruppen wie Studierende unterschiedlich bepreist werden."},
{"question": "2.1 Der Telekom-Anbieter Suncom möchte die Preise seiner Leistungen anpassen. d) Das Internet-Angebot Suncom Copper wird nur in Kombination mit Suncom TV angeboten und die Leistungskomponenten können nicht einzeln erworben werden. Dabei handelt es sich um ein reines Preisbündel.", "answer": "richtig", "explanation": "Reines Preisbündel bedeutet, dass Komponenten nicht separat erhältlich sind – hier zutreffend."},
{"question": "2.1 Der Telekom-Anbieter Suncom möchte die Preise seiner Leistungen anpassen. e) Das Internet-Angebot Suncom Lightning ist gleich schnell wie das Angebot von Konkurrent Swiss Wire. Suncom setzt den Preis auf CHF 99 / Monat und damit gleich hoch wie das Angebot von Swiss Wire. Das wird als kundenorientiertes Pricing bezeichnet.", "answer": "richtig", "explanation": "Kundenorientiertes Pricing orientiert sich am wahrgenommenen Nutzen bzw. Marktpreis – das passt."},
{"question": "2.2 Der Nahrungsmittelkonzern Imme AG hat sich entschieden, das Produktportfolio zu überarbeiten. a) Das Kaffeegetränk Caffeine Xpress enthielt in der ursprünglichen Rezeptur Inhaltsstoffe, welche die Fingernägel grün färbten. Der Hersteller Imme änderte die Rezeptur und ersetzt das alte Produkt 1/1. Dabei handelt es sich um eine Produktvarietät.", "answer": "falsch", "explanation": "Die Änderung der Rezeptur bei gleichem Produktnamen ist eine Leistungsvariation, keine neue Produktvarietät."},
{"question": "2.2 Der Nahrungsmittelkonzern Imme AG hat sich entschieden, das Produktportfolio zu überarbeiten. b) Der Hersteller Imme will nun auch noch einen Milchkaffee mit dem Namen Caffeine Xpress Milk anbieten. Bei Caffeine Xpress Milk handelt es sich um eine Leistungsvariation.", "answer": "richtig", "explanation": "Eine zusätzliche Produktvariante mit verändertem Inhalt fällt unter Leistungsvariation."},
{"question": "2.2 Der Nahrungsmittelkonzern Imme AG hat sich entschieden, das Produktportfolio zu überarbeiten. c) Das Produkt Caffeine Xpress soll zukünftig auch noch in den zwei neuen Geschmacksrichtungen Chocolate und Strawberry angeboten werden. Dabei handelt es sich um eine Produktdifferenzierung.", "answer": "richtig", "explanation": "Unterschiedliche Geschmacksrichtungen unter gleicher Marke entsprechen der Produktdifferenzierung."},
{"question": "2.2 Der Nahrungsmittelkonzern Imme AG hat sich entschieden, das Produktportfolio zu überarbeiten. d) Imme legt im Deckel der Caffeine Xpress jeweils Zettel bei mit Wandersinspirationen. Dabei handelt es sich um einen Value-Added-Service.", "answer": "richtig", "explanation": "Zusätzliche, nicht unmittelbar produktbezogene Leistungen sind typische Value-Added-Services."},
{"question": "2.2 Der Nahrungsmittelkonzern Imme AG hat sich entschieden, das Produktportfolio zu überarbeiten. e) Nach zwei Jahren Produktion von Caffeine Xpress entscheidet sich Imme, keine Kaffeegetränke mehr herzustellen und nimmt die Produkte vom Markt. In der Nachlaufphase des Produktlebenszyklus ist es nicht mehr möglich, dass Verluste entstehen.", "answer": "falsch", "explanation": "Auch in der Nachlaufphase können bei falschem Timing oder Abschreibungen Verluste entstehen."},
{"question": "2.3 Das Handelsunternehmen Glov überarbeitet seine Kommunikationsstrategie. a) Glov will ihre Kunden dazu animieren, die Produkte der Fitness-orientierten Marke GainZ zu kaufen. Dabei handelt es sich um ein konatives Kommunikationsziel.", "answer": "richtig", "explanation": "Ein konatives Ziel zielt auf Verhalten, hier den Kaufimpuls."},
{"question": "2.3 Das Handelsunternehmen Glov überarbeitet seine Kommunikationsstrategie. b) Glov lässt an den Bahnhöfen Plakate aufhängen mit Werbebotschaften der Marke GainZ. Sie wollen damit die Markenbekanntheit stärken. Dabei handelt es sich um ein affektives Kommunikationsziel.", "answer": "falsch", "explanation": "Markenbekanntheit ist ein kognitives, nicht affektives Ziel."},
{"question": "2.3 Das Handelsunternehmen Glov überarbeitet seine Kommunikationsstrategie. c) Für eine einzigartige Leistung soll auch die Kommunikation einzigartig sein. Glov entwickelt daher eine Unique Communications Proposition, also eine UCP.", "answer": "richtig", "explanation": "Eine UCP stellt ein Alleinstellungsmerkmal in der Kommunikation dar."},
{"question": "2.3 Das Handelsunternehmen Glov überarbeitet seine Kommunikationsstrategie. d) Glov stellt Degustationsstände in den Filialen auf, bei denen Kunden die GainZ Produkte probieren können. Dabei handelt es sich um Verkaufsförderung.", "answer": "richtig", "explanation": "Produktproben sind eine klassische Maßnahme der Verkaufsförderung."},
{"question": "2.3 Das Handelsunternehmen Glov überarbeitet seine Kommunikationsstrategie. e) Glov schickt dem lokalen Fussballverein jeden Monat 1000 Stück GainZ Proteinriegel. Dabei handelt es sich um eine Form von Sponsoring.", "answer": "richtig", "explanation": "Produktbereitstellung an Vereine ist typisches Sponsoring."},
{"question": "2.4 Das Start-up EcoFood Solutions plant, eine innovative Verpackungslösung für umweltfreundliche Lebensmittelverpackungen auf den Markt zu bringen. In welchem Stadium des Planungsprozesses wäre die Anwendung der Porter's Five Forces-Analyse am besten geeignet? a) Während der Entwicklung des technischen Designs und der Materialauswahl für die Verpackung.", "answer": "falsch", "explanation": "Die technische Produktentwicklung ist nicht Gegenstand der Porter's-Analyse."},
{"question": "2.4 Das Start-up EcoFood Solutions plant, eine innovative Verpackungslösung für umweltfreundliche Lebensmittelverpackungen auf den Markt zu bringen. In welchem Stadium des Planungsprozesses wäre die Anwendung der Porter's Five Forces-Analyse am besten geeignet? b) Bei der Festlegung der Preisstrategie und der Berechnung der Herstellungskosten für das Produkt.", "answer": "falsch", "explanation": "Kosten- und Preisberechnungen sind nicht Fokus von Porter's Wettbewerbskräfte."},
{"question": "2.4 Das Start-up EcoFood Solutions plant, eine innovative Verpackungslösung für umweltfreundliche Lebensmittelverpackungen auf den Markt zu bringen. In welchem Stadium des Planungsprozesses wäre die Anwendung der Porter's Five Forces-Analyse am besten geeignet? c) Bei der Auswahl der Zielgruppe und der Gestaltung der Werbebotschaft für die Markteinführung.", "answer": "falsch", "explanation": "Porter bezieht sich auf Marktstrukturen, nicht auf Zielgruppenwahl oder Werbestrategie."},
{"question": "2.4 Das Start-up EcoFood Solutions plant, eine innovative Verpackungslösung für umweltfreundliche Lebensmittelverpackungen auf den Markt zu bringen. In welchem Stadium des Planungsprozesses wäre die Anwendung der Porter's Five Forces-Analyse am besten geeignet? d) Bei der Analyse des Wettbewerbsdrucks und der Identifizierung von Bedrohungen durch bestehende Unternehmen auf dem Markt.", "answer": "richtig", "explanation": "Dies ist der zentrale Anwendungsbereich der Five Forces-Analyse."},
{"question": "2.4 Das Start-up EcoFood Solutions plant, eine innovative Verpackungslösung für umweltfreundliche Lebensmittelverpackungen auf den Markt zu bringen. In welchem Stadium des Planungsprozesses wäre die Anwendung der Porter's Five Forces-Analyse am besten geeignet? e) Bei der Suche nach Finanzierungsquellen und Investoren für das Projekt.", "answer": "falsch", "explanation": "Finanzierungsentscheidungen fallen nicht in den Geltungsbereich der Wettbewerbsanalyse nach Porter."},
{"question": "1.1 a) Das Pricing ist deshalb von besonderer Bedeutung im Marketing-Mix, weil es einen direkten Einfluss auf die Unternehmenskennzahlen hat.", "answer": "richtig", "explanation": "Pricing beeinflusst direkt Umsatz und Gewinn, daher ist es zentral im Marketing-Mix."},
{"question": "1.1 b) Der Prestigeeffekt des Preises beschreibt eine sinkende Absatzmenge nach einer Preiserhöhung.", "answer": "falsch", "explanation": "Der Prestigeeffekt beschreibt steigende Nachfrage durch höheren Preis wegen Prestige, nicht sinkende."},
{"question": "1.1 c) Der Preisankereffekt beschreibt, dass Kund:innen einen bereits bekannten Preis als Referenzwert herbeiziehen, um einen neuen Preis im Rahmen einer Kaufentscheidung einzustufen.", "answer": "richtig", "explanation": "Das ist korrekt – der Preisanker beeinflusst die Preiswahrnehmung."},
{"question": "1.1 d) Ein Bluetooth-Kopfhörer kostet CHF 100, die variablen Produktionskosten entsprechen CHF 60 pro Stück und die Fixkosten CHF 10'000. Von den Kopfhörern verkaufen Sie 1'000 Stück. Der resultierende Gewinn beträgt CHF 30'000.", "answer": "richtig", "explanation": "Einnahmen: 100'000, Ausgaben: 60'000 + 10'000 = 70'000 → Gewinn: 30'000."},
{"question": "1.2 a) Die variablen Stückkosten sind der effektivste Gewinntreiber. D.h. eine 10%-ige Verbesserung der variablen Stückkosten erhöht den Gewinn am stärksten verglichen mit dem Preis, der Absatzmenge und den Fixkosten.", "answer": "falsch", "explanation": "Der Preis ist der stärkste Gewinntreiber, nicht die variablen Kosten."},
{"question": "1.2 b) Kundenorientierte Preissetzung (im Kontext des Magischen Dreiecks des Pricings) bedeutet, dass man die Preise so tief setzt, dass gerade die Kosten gedeckt sind.", "answer": "falsch", "explanation": "Kundenorientierung heißt, am Zahlungswillen der Kunden auszurichten – nicht kostenbasiert."},
{"question": "1.2 c) Im Rahmen der Preispositionierung wird eine hohe Qualität zu tiefen Preisen als Übervorteilungsstrategie bezeichnet.", "answer": "falsch", "explanation": "Übervorteilung = hohe Preise bei niedriger Qualität, nicht umgekehrt."},
{"question": "1.2 d) Bei der Penetrationsstrategie ist der Preis bei der Produkteinführung hoch und wird dann über die Zeit reduziert.", "answer": "falsch", "explanation": "Bei Penetration ist der Preis zu Beginn niedrig, um Marktanteile zu gewinnen."},
{"question": "1.3 a) Der Autohersteller WMB verkauft seine Fahrzeuge in den USA zu einem höheren Preis als in China. Das wird als «personelle Preisdifferenzierung» bezeichnet.", "answer": "richtig", "explanation": "Preisunterschiede je nach Käufergruppe oder Markt sind typische Merkmale personeller Preisdifferenzierung."},
{"question": "1.3 b) Im Kontext von Preisbündelung spricht man von «reinen» Preisbündeln, wenn die Leistungskomponenten auch einzeln erhältlich sind, von «gemischten» Preisbündeln, wenn die Leistungskomponenten nicht einzeln erhältlich sind.", "answer": "falsch", "explanation": "Die Begriffe sind vertauscht: Reines Bündel = nicht einzeln erhältlich, gemischtes Bündel = einzeln erhältlich."},
{"question": "1.3 c) Die Schawarma Kings AG verkauft im Januar 800 Stück Schawarmas mit Pouletfleisch zu CHF 9 und nach einer Preissenkung im Februar 1000 Stück zu CHF 8. Die daraus abgeleitete Preisabsatzfunktion ist p(x) = 13 - 1/200x.", "answer": "richtig", "explanation": "Die Werte korrekt eingesetzt ergeben diese lineare Funktion."},
{"question": "1.3 d) Sie nehmen obige Preisabsatzfunktion und berechnen, dass bei einem Preis von CHF 7 die abgesetzte Menge 1200 Stück betragen würde. Zudem identifizieren Sie die Sättigungsmenge bei 2600 Stück und den Prohibitionspreis bei CHF 13.", "answer": "richtig", "explanation": "Rechnerisch korrekt, basierend auf der gegebenen Funktion."},
{"question": "1.4 a) Das Stage-Gate-Modell hat im Wesentlichen zum Ziel, Risiken in der Produktentwicklung zu minimieren.", "answer": "richtig", "explanation": "Das Stage-Gate-Modell strukturiert den Innovationsprozess in Stufen und Gates zur Risikominimierung."},
{"question": "1.4 b) Scrum eignet sich vor allem für die Entwicklung von komplexen Leistungen im Dienstleistungsbereich.", "answer": "richtig", "explanation": "Scrum ist flexibel und kollaborativ – ideal für dynamische Dienstleistungen."},
{"question": "1.4 c) Ein langsameres Wachstum des Absatzes/Umsatzes/Gewinns ist ein Indikator, dass sich ein Produkt in der Reifephase im Produktlebenszyklus befindet.", "answer": "richtig", "explanation": "Typisches Merkmal der Reifephase ist ein verlangsamtes Wachstum."},
{"question": "1.4 d) In der Reifephase beschäftigt sich das Marketing hauptsächlich mit der Leistungspflege, um Umsätze bzw. Gewinne zu maximieren.", "answer": "richtig", "explanation": "In der Reifephase liegt der Fokus auf Produktpflege und Markterhalt."},
{"question": "1.5 a) Diversifikation eines Produktportfolios kann horizontal, vertikal oder lateral erfolgen.", "answer": "richtig", "explanation": "Das sind die drei klassischen Formen der Diversifikation."},
{"question": "1.5 b) Das Anbieten von Joghurts in verschiedenen Geschmacksrichtungen entspricht dem Konzept der Produktvarietät.", "answer": "richtig", "explanation": "Mehrere Varianten eines Grundprodukts sind ein Beispiel für Produktvarietät."},
{"question": "1.5 c) (Mass-)Customization ist ein Spezialfall der Produktdifferenzierung und erfüllt individuelle Kundenbedürfnisse mittels einer eigenen Variante.", "answer": "richtig", "explanation": "Mass Customization zielt auf Individualisierung in der Massenproduktion."},
{"question": "1.5 d) Vorwärtsintegration ist, wenn z.B. ein Autohersteller damit beginnt, auch noch Motorräder herzustellen. Horizontale Diversifikation ist, wenn z.B. ein Autohersteller eine eigene Distribution aufbaut.", "answer": "falsch", "explanation": "Die Begriffe sind vertauscht: Eigene Distribution = Vorwärtsintegration, neues Produkt = horizontale Diversifikation."},
{"question": "1.6 a) Die Service Profit Chain zeigt die Wirkung zufriedener Mitarbeitenden auf die Zufriedenheit der Kund:innen.", "answer": "richtig", "explanation": "Zufriedene Mitarbeitende → bessere Leistung → zufriedene Kund:innen → Unternehmenserfolg."},
{"question": "1.6 b) «Customer Managed Relationship» bezeichnet den Ansatz, dass das Unternehmen die Beziehung zu Kund:innen bestimmt.", "answer": "falsch", "explanation": "Bei CMR bestimmen die Kund:innen die Beziehungsintensität, nicht das Unternehmen."},
{"question": "1.6 c) «Cross-Selling» bezeichnet den Verkauf eines Upgrades einer Leistung. «Up-Selling» hingegen der Verkauf einer zusätzlichen, dazugehörigen Leistung.", "answer": "falsch", "explanation": "Die Definitionen sind vertauscht: Cross-Selling = Zusatzprodukt, Up-Selling = höherwertiges Produkt."},
{"question": "1.6 d) «Verbundenheit» bezeichnet die faktische Kundschaftsbindung, welche z.B. durch Verträge erzwungen werden kann. «Gebundenheit» hingegen bezeichnet die emotionale Kundschaftsbindung.", "answer": "falsch", "explanation": "Auch hier sind die Begriffe vertauscht: Gebundenheit = vertraglich, Verbundenheit = emotional."},
{"question": "1.7 a) «Fading away» im Kündigungsmanagement bedeutet, dass ein Unternehmen eine Kundschaftsbeziehung «versanden» lässt und z.B. keine Newsletter mehr versendet.", "answer": "richtig", "explanation": "Das beschreibt das passive Auslaufenlassen einer Beziehung."},
{"question": "1.7 b) Das Beschwerdeparadoxon beschreibt, dass Kunden bei einer Reklamation, die positiv bearbeitet wurde, hinterher zufriedener sind als Kunden, die nichts zu beanstanden hatten.", "answer": "richtig", "explanation": "Positive Bearbeitung kann zu höherer Loyalität führen als keine Probleme."},
{"question": "1.7 c) Der Inbound-Marketing-Ansatz umfasst u.a. Content-Marketing, SEO und Social Media Marketing.", "answer": "richtig", "explanation": "Inbound-Marketing zielt auf Anziehung durch Mehrwert und Inhalte."},
{"question": "1.7 d) Nach dem Confirmation-Disconfirmation-Paradigma entsteht Kundenzufriedenheit durch einen Vergleichsprozess zwischen Ist- und Soll-Leistung.", "answer": "richtig", "explanation": "Zufriedenheit ergibt sich, wenn Erwartungen erfüllt oder übertroffen werden."},
{"question": "1.8 a) Das wertorientierte Kundenmanagement verfolgt als zentrales Ziel, den Aufbau eines möglichst grossen Kundenstamms unabhängig von der Profitabilität der Kunden.", "answer": "falsch", "explanation": "Es geht gezielt um profitable Kundenbeziehungen, nicht um möglichst viele."},
{"question": "1.8 b) Der Customer Lifetime Value ist in seiner Grundform eine eindimensionale und zukunftsbezogene Form der Kundenwertberechnung.", "answer": "richtig", "explanation": "Der CLV prognostiziert den zukünftigen Wert eines Kunden."},
{"question": "1.8 c) Es sei gegeben: E₀ = 200, K₀ = 300, r = 6%, E₁ = ... = E₄ = 200, K₁ = ... = K₄ = 50. Der Customer Lifetime Value ist (gerundet): CLV ≈ 420.", "answer": "richtig", "explanation": "Die Berechnung ergibt tatsächlich CLV ≈ 420."},
{"question": "1.8 d) Scoring Modelle zur Ermittlung des Customer Values sind flexibel und erlauben die Berücksichtigung von qualitativen wie auch quantitativen Kriterien.", "answer": "richtig", "explanation": "Scoring-Modelle kombinieren harte und weiche Faktoren."},
{"question": "1.9 a) Die Unique Communications Proposition (UCP) wird häufig über eine unverkennbare Marke und ein stringentes einheitliches Design sämtlicher Kommunikationsinstrumente und -auftritte erzielt.", "answer": "richtig", "explanation": "UCP zielt auf ein einheitliches, unverwechselbares Kommunikationsprofil ab."},
{"question": "1.9 b) Einstellung, Image sowie Kaufabsicht werden zu den kognitiven Kommunikationszielen gezählt.", "answer": "falsch", "explanation": "Diese Begriffe zählen zu affektiven oder konativen Zielen, nicht zu kognitiven."},
{"question": "1.9 c) Die Grundidee von integrierter Kommunikation ist, dass verschiedene Kommunikationsmaßnahmen aufeinander abgestimmt sein sollten, um eine maximale Wirkung zu entfalten.", "answer": "richtig", "explanation": "Integrierte Kommunikation erfordert Konsistenz über alle Kanäle hinweg."},
{"question": "1.9 d) Bei der inhaltlichen Integration geht es u.a. um einheitliche Logos und Schriftarten.", "answer": "falsch", "explanation": "Einheitliche Logos/Schriften betreffen die formale, nicht die inhaltliche Integration."},
  {"question": "1.10 a) Beispiele für Mediawerbung sind u.a. Printanzeigen, Plakate und Kinowerbung.", "answer": "richtig", "explanation": "Diese Werbemittel zählen zur klassischen Mediawerbung."},
  {"question": "1.10 b) Public Relations hat vorrangig zum Ziel Verständnis und Vertrauen zu schaffen.", "answer": "richtig", "explanation": "PR zielt auf langfristige Beziehungspflege, nicht direkt auf Absatz."},
  {"question": "1.10 c) Mit Sponsoring fördern Unternehmen Personen und/oder Organisationen in den Bereichen Sport, Kultur, Soziales, Umwelt und/oder den Medien, um damit u.a. ihre Kommunikationsziele zu erreichen.", "answer": "richtig", "explanation": "Sponsoring dient der Kommunikationswirkung und Imagepflege."},
  {"question": "1.10 d) Im Rahmen von Product Placement integrieren Unternehmen ihre Produkte oder ihre Marke in ein anderes Werk und bezahlen i.d.R. für die Platzierung.", "answer": "richtig", "explanation": "Product Placement ist bezahlte Markenintegration in Medieninhalte."},
  {"question": "1.11 a) Im Block 'Schlüsselpartnerschaften' sollten die Gründerinnen die physischen, intellektuellen und menschlichen Ressourcen eintragen, die ihr Unternehmen benötigt.", "answer": "falsch", "explanation": "Diese gehören in den Block 'Schlüsselressourcen'; hier geht es um Partner."},
  {"question": "1.11 b) Mit der 'Value Proposition' müssen die Gründerinnen beschreiben, wie das Unternehmen Geld verdienen wird und über welche Vertriebskanäle der Value erwirtschaftet wird.", "answer": "falsch", "explanation": "Die Value Proposition beschreibt den Kundennutzen, nicht die Kanäle."},
  {"question": "1.11 c) Im Block 'Kundenbeziehungen', sollten die Gründerinnen beschreiben, welche Art von Beziehung zu jedem Kundensegment geschaffen und aufrechterhalten wird, und sie erklären, wie Kunden geworben und gehalten werden.", "answer": "richtig", "explanation": "Dies ist die korrekte Beschreibung des Blocks 'Kundenbeziehungen'."},
  {"question": "1.11 d) Bei der Erarbeitung der 'Zielgruppen', müssen die Gründerinnen definieren welche Kundensegmente für ihr Startup relevant sind.", "answer": "richtig", "explanation": "Zielgruppenanalyse gehört zum Block 'Kundensegmente'."},
  {"question": "1.12 a) Chancen und Risiken werden aus den unternehmensinternen Faktoren abgeleitet.", "answer": "falsch", "explanation": "Chancen und Risiken leiten sich aus externen, nicht internen Faktoren ab."},
  {"question": "1.12 b) Stärken und Schwächen beschreiben Faktoren, die das Unternehmen nur schwer selber beeinflussen kann.", "answer": "falsch", "explanation": "Stärken und Schwächen sind interne Faktoren, die das Unternehmen sehr wohl beeinflussen kann."},
  {"question": "1.12 c) Die Analyse der Marktfaktoren gehört zur unternehmensexternen Sicht.", "answer": "richtig", "explanation": "Marktfaktoren sind externe Einflussgrößen."},
  {"question": "1.12 d) Der Business Model Canvas ist ein geeignetes Werkzeug, um die unternehmensinternen Faktoren systematisch zu erfassen.", "answer": "richtig", "explanation": "Das Tool hilft bei der strukturierten Darstellung interner Komponenten."},
  {"question": "1.13 a) Value Proposition und Kundenprofil werden getrennt analysiert.", "answer": "richtig", "explanation": "Beide Seiten (Kundensicht und Unternehmenssicht) sind getrennte Bestandteile des Canvas."},
  {"question": "1.13 b) Bei der Value Proposition wird detaillierter beschrieben wie das Unternehmen Geld verdient und über welche Vertriebskanäle der Value erwirtschaftet wird.", "answer": "falsch", "explanation": "Die Vertriebskanäle gehören nicht zur Value Proposition, sondern zum Block 'Kanäle'."},
  {"question": "1.13 c) Beim Kundenprofil werden die Probleme, Aufgaben und Nutzen aus Sicht der Kund:innen beschrieben.", "answer": "richtig", "explanation": "Dies ist die zentrale Aufgabe des Kundenprofils."},
  {"question": "1.13 d) Funktionelle Aufgaben bezeichnen Aufgaben, die einen spezifischen Auftrag enthalten oder ein spezifisches Problem lösen wollen.", "answer": "richtig", "explanation": "Dies entspricht der Definition funktioneller Kundenaufgaben."},
  {"question": "1.14 a) Im Bereich seltene Erden dominiert China den Markt, vor den USA, Myanmar und Australien. Das ist für Tesla im Kontext einer Five Forces Analyse nicht relevant, weil Tesla in China bereits eine starke Präsenz hat.", "answer": "falsch", "explanation": "Auch mit starker Präsenz ist die Lieferantenmacht ein relevanter Faktor."},
  {"question": "1.14 b) Die Verhandlungsmacht der Abnehmer ist ein wesentlicher Faktor des Five Forces Modells.", "answer": "richtig", "explanation": "Das ist eine der fünf Kräfte im Modell."},
  {"question": "1.14 c) Im Five Forces Modell werden sowohl bestehende Wettbewerber wie auch potenzielle neue Konkurrenten analysiert.", "answer": "richtig", "explanation": "Das Modell betrachtet auch die Bedrohung durch neue Marktteilnehmer."},
  {"question": "1.14 d) Das Auslaufen eines Patents ist im Five Forces Modell relevant, weil dadurch eine Bedrohung durch Substitute entstehen kann.", "answer": "richtig", "explanation": "Durch Patentauslauf steigen Substitutionsmöglichkeiten."},
  {"question": "1.15 a) Die Anwendung von SEO-Maßnahmen führt dazu, dass bezahlte Werbung (SEA) weniger relevant wird und somit in einem umfassenden digitalen Marketingplan vernachlässigt werden kann.", "answer": "falsch", "explanation": "SEO und SEA ergänzen sich und sollten gemeinsam betrachtet werden."},
  {"question": "1.15 b) Durch SEA-Kampagnen kann 'Bücherwelt' gezielt Werbung für spezifische Autoren oder Buchtitel schalten, um direkt die gewünschte Zielgruppe anzusprechen.", "answer": "richtig", "explanation": "SEA erlaubt gezielte Ansprache durch Keyword-Targeting."},
  {"question": "1.15 c) Die Ausgaben und die Gestaltung der SEA-Kampagnen haben keine Auswirkungen auf die Positionierung von 'Bücherwelt' in den organischen Suchergebnissen.", "answer": "richtig", "explanation": "SEA beeinflusst bezahlte, aber nicht organische Suchergebnisse."},
  {"question": "1.15 d) Nachdem 'Bücherwelt' ihre Website für bessere SEO-Ergebnisse optimiert hat, kann sie erwarten, dass die Änderungen unmittelbar eine Verbesserung der Suchrankings bewirken.", "answer": "falsch", "explanation": "SEO-Wirkung zeigt sich meist verzögert, nicht sofort."},
  {"question": "1.16 a) Das Anbieten einer konstanten Belohnung nach jeder Nutzung der App ist der effektivste Weg, um Nutzer zu motivieren, die App regelmäßig zu verwenden.", "answer": "falsch", "explanation": "Variable Belohnung ist wirksamer als konstante Belohnung (Hook-Modell)."},
  {"question": "1.16 b) Push Notifikationen der TimingTiger App sind gemäß dem Hook-Modell interne Trigger für die Nutzung, weil sie durch die App ausgespielt werden.", "answer": "falsch", "explanation": "Push-Benachrichtigungen sind externe Trigger, nicht intern."},
  {"question": "1.16 c) Die Möglichkeit für Nutzer, Inhalte innerhalb der App zu personalisieren, fördert die Investition und steigert damit langfristig die Nutzerbindung.", "answer": "richtig", "explanation": "Personalisierung schafft Relevanz und fördert Engagement."},
  {"question": "1.16 d) Die Aktion, die vom Nutzer erwartet wird, sollte möglichst komplex gestaltet sein, um das Engagement zu erhöhen.", "answer": "falsch", "explanation": "Laut Hook-Modell sollte die gewünschte Aktion möglichst einfach sein."},
{"question": "1.17 a) Die \"Churn Rate\" zeigt auf, wie erfolgreich \"StyleFirst\" darin ist, ihre Bestandskunden zu halten, indem sie misst, wie viele Kunden innerhalb eines bestimmten Zeitraums die Marke verlassen.", "answer": "richtig", "explanation": "Die Churn Rate misst die Kundenabwanderung und zeigt auf, wie gut ein Unternehmen seine Kunden halten kann."},
{"question": "1.17 b) «StyleFirst» nutzt den \"Net Promoter Score (NPS)\" um zu ermitteln, wie effektiv ihre letzte Modekampagne im Vergleich zu Wettbewerbern war.", "answer": "richtig", "explanation": "Der NPS misst die Wahrscheinlichkeit, mit der Kunden ein Unternehmen weiterempfehlen würden."},
{"question": "1.17 c) Der \"Customer Lifetime Value (CLV)\" stellt den durchschnittlichen Umsatz dar, den ein Kunde innerhalb eines Jahres generiert.", "answer": "falsch", "explanation": "Der CLV bezieht sich auf den Gesamtumsatz über die gesamte Kundenbeziehung, nicht nur auf ein Jahr."},
{"question": "1.17 d) \"Organic Reach\" auf Plattformen wie Instagram und Facebook misst die Anzahl der Nutzer, die Inhalte durch Empfehlungen und Teilen erreichen, unabhängig von direkten Werbeausgaben.", "answer": "richtig", "explanation": "Organic Reach beschreibt die unbezahlte Reichweite durch Interaktion wie Teilen und Kommentieren."},
{"question": "1.18 a) Ein Beispiel für aktive Marketingautomatisierung ist das Auslösen einer speziellen Rabatt-E-Mail an einen Kunden, nachdem dieser ein Produkt in den Warenkorb gelegt, aber den Kauf nicht abgeschlossen hat.", "answer": "richtig", "explanation": "Personalisierte E-Mails auf Basis von Nutzerverhalten zählen zur aktiven Automatisierung."},
{"question": "1.18 b) Kleine Start-Ups wie «EcoWear» setzen häufig auf Automatisierungslösungen wie Salesforce oder SAP weil diese sehr günstig, dafür aber funktional stark begrenzt sind.", "answer": "richtig", "explanation": "Kostengünstige Tools sind oft limitiert, werden aber in kleinen Unternehmen häufig genutzt."},
{"question": "1.18 c) Aktive Marketingautomatisierung erfordert, dass das Marketingteam manuell Daten analysiert und auf der Basis dieser Analysen Kampagnen plant und umsetzt.", "answer": "falsch", "explanation": "Aktive Automatisierung funktioniert automatisiert auf Basis von Algorithmen, nicht manuell."},
{"question": "1.18 d) Die Generierung von regelmäßigen Leistungsberichten über das Nutzerverhalten auf der Website, ohne dass ein direktes Kundenfeedback vorliegt, ist ein Beispiel für passive Marketingautomatisierung.", "answer": "richtig", "explanation": "Passive Automatisierung umfasst Berichte und Analyseprozesse ohne direkte Kundeninteraktion."},
{"question": "2.1 a) Der Telekom-Anbieter Helvecom möchte die Preise seiner Leistungen anpassen. Helvecom hatte ursprünglich 1 tiefpreisigen und 1 mittelpreisigen Router im Angebot, wobei meist der tiefpreisige gekauft wurde. Nachdem noch ein hochpreisiger Premium-Router ins Sortiment aufgenommen wurde, wird nun der mittelpreisige Router am meisten verkauft. Das ist der sog. Prestigeeffekt des Preises.", "answer": "falsch", "explanation": "Das beschriebene Verhalten entspricht dem Kompromisseffekt, nicht dem Prestigeeffekt."},
{"question": "2.1 b) Der Telekom-Anbieter Helvecom möchte die Preise seiner Leistungen anpassen. Helvecom verkauft das neue Smartphone Lexip 8. Am Anfang kostet das Phone CHF 500 und wird dann über die Zeit immer teurer. Das wird als Skimmingstrategie bezeichnet.", "answer": "falsch", "explanation": "Bei der Skimmingstrategie ist der Preis zu Beginn hoch und sinkt im Laufe der Zeit. Hier ist es umgekehrt."},
{"question": "2.1 c) Der Telekom-Anbieter Helvecom möchte die Preise seiner Leistungen anpassen. Das Internet-Angebot Helvecom Fast Glass ist in der Deutschschweiz teurer als in der Westschweiz. Das ist eine Form der personellen Preisdifferenzierung.", "answer": "falsch", "explanation": "Preisunterschiede nach Regionen fallen unter geografische Preisdifferenzierung, nicht personelle."},
{"question": "2.1 d) Der Telekom-Anbieter Helvecom möchte die Preise seiner Leistungen anpassen. Das Internet-Angebot Helvecom Rather Slow Glass wird nur in Kombination mit Helvecom TV angeboten und die Leistungskomponenten können nicht einzeln erworben werden. Dabei handelt es sich um ein gemischtes Preisbündel.", "answer": "richtig", "explanation": "Ein gemischtes Preisbündel liegt vor, wenn Einzelleistungen zwar verfügbar, aber im Bundle günstiger oder exklusiv kombiniert werden."},
{"question": "2.1 e) Der Telekom-Anbieter Helvecom möchte die Preise seiner Leistungen anpassen. Das Internet-Angebot Helvecom Lightning Fast Glass ist konkurrenzlos schnell. Helvecom setzt den Preis auf CHF 99 / Monat und reizt damit die Zahlungsbereitschaft der Kunden maximal aus. Das wird als kundenorientiertes Pricing (engl. Value-Based Pricing) bezeichnet.", "answer": "richtig", "explanation": "Value-Based Pricing orientiert sich an der Zahlungsbereitschaft der Kunden, wie im Beispiel beschrieben."},
{"question": "Der internationale Nahrungsmittelkonzern Duolever AG hat entschieden, das Produktportfolio zu überarbeiten. 2.2 a) Das Produkt CafésSimo enthielt in der ursprünglichen Rezeptur einen Zusatzstoff, der im Verdacht steht, bei den Konsumenten zu einer leichten Grünfärbung der Haare zu führen. Duolever ändert die Rezeptur und ersetzt das alte Produkt 1/1. Dabei handelt es sich um eine Leistungsvariation.", "answer": "richtig", "explanation": "Das Ersetzen eines Produkts mit gleicher Funktion, aber verbesserter Rezeptur ist eine klassische Leistungsvariation."},
{"question": "Der internationale Nahrungsmittelkonzern Duolever AG hat entschieden, das Produktportfolio zu überarbeiten. 2.2 b) Der Milchkaffee CafésSimo Tasty Milk soll neu auch ohne Lactose (Milchzucker) angeboten werden. Bei CafésSimo Tasty Milk Free handelt es sich um eine Produktdifferenzierung.", "answer": "falsch", "explanation": "Das ist eine Produktvarietät – es bleibt das gleiche Grundprodukt, nur eine Variante ohne Lactose."},
{"question": "Der internationale Nahrungsmittelkonzern Duolever AG hat entschieden, das Produktportfolio zu überarbeiten. 2.2 c) Das Produkt CafésSimo ist ein schon etwas altbackenes Traditionsprodukt und hat seit Jahren rückläufige Umsätze. Duolever entscheidet sich dazu, das Produkt in Café Grande Gusto umzubranden und gleichzeitig auch das Verpackungsdesign, das Pricing und die Werbebotschaft anzupassen. Das ist ein typisches Beispiel eines Relaunches.", "answer": "richtig", "explanation": "Rebranding in Kombination mit Design- und Kommunikationsanpassung ist ein klassischer Relaunch."},
{"question": "Der internationale Nahrungsmittelkonzern Duolever AG hat entschieden, das Produktportfolio zu überarbeiten. 2.2 d) Das Produkt Café Grande Gusto soll zukünftig auch noch in den zwei neuen Geschmacksrichtungen Nocciola und Vaniglia angeboten werden. Dabei handelt es sich um eine horizontale Diversifikation.", "answer": "falsch", "explanation": "Es handelt sich um eine Produktdifferenzierung, nicht um eine Diversifikation – das Grundprodukt bleibt erhalten."},
{"question": "Der internationale Nahrungsmittelkonzern Duolever AG hat entschieden, das Produktportfolio zu überarbeiten. 2.2 e) Duolever entschliesst sich auf die Verpackung von Café Grande Gusto Rezeptideen abzudrucken. Dabei handelt es sich um einen Value-Added-Service.", "answer": "richtig", "explanation": "Zusätzliche Informationen oder Services auf Verpackungen gelten als Value-Added-Services."},
{"question": "Das Handelsunternehmen Sorgim überarbeitet seine Kommunikationsstrategie. 2.3 a) Sorgim will ihre vegane Marke Vegs stärker bekannt machen. Das ist ein kognitives Kommunikationsziel.", "answer": "richtig", "explanation": "Bekanntmachung einer Marke fällt unter kognitive Ziele, da es um Wissen und Aufmerksamkeit geht."},
{"question": "Das Handelsunternehmen Sorgim überarbeitet seine Kommunikationsstrategie. 2.3 b) Sorgim lässt an den Bahnhöfen Plakate aufhängen mit Angeboten der Marke Vegs. Sie wollen damit die Kunden zum Kauf der Produkte bewegen. Das ist ein konatives Kommunikationsziel.", "answer": "richtig", "explanation": "Konative Ziele zielen auf eine konkrete Handlung ab, wie z.B. den Kauf."},
{"question": "Das Handelsunternehmen Sorgim überarbeitet seine Kommunikationsstrategie. 2.3 c) Für eine einzigartige Leistung soll auch die Kommunikation einzigartig sein. Sorgim entwickelt daher eine Unique Communications Proposition, also eine UCP.", "answer": "richtig", "explanation": "UCP steht für ein einzigartiges Kommunikationsversprechen – passend zur Leistung."},
{"question": "Das Handelsunternehmen Sorgim überarbeitet seine Kommunikationsstrategie. 2.3 d) Sorgim stellt Degustationsstände in den Filialen auf, bei denen Kunden die Vegs Produkte probieren können. Dabei handelt es sich um Verkaufsförderung.", "answer": "richtig", "explanation": "Produktproben vor Ort sind typische Maßnahmen der Verkaufsförderung."},
{"question": "Das Handelsunternehmen Sorgim überarbeitet seine Kommunikationsstrategie. 2.3 e) Sorgim schickt dem lokalen Fussballverein jeden Monat 1000 Stück Vegs Proteinriegel. Dabei handelt es sich um eine Form von Public Relations.", "answer": "falsch", "explanation": "Dies ist Sponsoring, nicht PR – es wird eine Leistung mit Gegenwert erbracht."},
{"question": "Das Start-up 'Healthinnovate' plant, eine revolutionäre Software zur Verbesserung der Patientenbetreuung im Gesundheitssektor zu entwickeln. In welchem Stadium des Planungsprozesses wäre der Einsatz einer PESTEL-Analyse besonders vorteilhaft? 2.4 a) Beim Bewerten des breiten makroökonomischen Umfelds, um externe Einflüsse auf das Projekt zu verstehen.", "answer": "richtig", "explanation": "Die PESTEL-Analyse dient der Untersuchung externer Umweltfaktoren und ist besonders zu Beginn strategischer Planungen nützlich."},
{"question": "Das Start-up 'Healthinnovate' plant, eine revolutionäre Software zur Verbesserung der Patientenbetreuung im Gesundheitssektor zu entwickeln. In welchem Stadium des Planungsprozesses wäre der Einsatz einer PESTEL-Analyse besonders vorteilhaft? 2.4 b) Während der Gestaltung der Benutzeroberfläche und der Erfahrung, die Endnutzer mit der Software haben werden.", "answer": "falsch", "explanation": "Die Gestaltung der Benutzeroberfläche ist eine interne Entwicklungsaufgabe, für die die PESTEL-Analyse keine Relevanz hat."},
{"question": "Das Start-up 'Healthinnovate' plant, eine revolutionäre Software zur Verbesserung der Patientenbetreuung im Gesundheitssektor zu entwickeln. In welchem Stadium des Planungsprozesses wäre der Einsatz einer PESTEL-Analyse besonders vorteilhaft? 2.4 c) Bei der Entscheidung, welche Programmiersprachen für die Entwicklung der Software verwendet werden sollen.", "answer": "falsch", "explanation": "Technologische Entwicklungsentscheidungen fallen nicht in den Anwendungsbereich der PESTEL-Analyse."},
{"question": "Das Start-up 'Healthinnovate' plant, eine revolutionäre Software zur Verbesserung der Patientenbetreuung im Gesundheitssektor zu entwickeln. In welchem Stadium des Planungsprozesses wäre der Einsatz einer PESTEL-Analyse besonders vorteilhaft? 2.4 d) Bei der Kalkulation der initialen Investitionskosten und der Finanzierungsstrategie für das Projekt.", "answer": "falsch", "explanation": "Finanzkalkulationen betreffen interne Faktoren und sind nicht Bestandteil einer PESTEL-Analyse."},
{"question": "Das Start-up 'Healthinnovate' plant, eine revolutionäre Software zur Verbesserung der Patientenbetreuung im Gesundheitssektor zu entwickeln. In welchem Stadium des Planungsprozesses wäre der Einsatz einer PESTEL-Analyse besonders vorteilhaft? 2.4 e) Bei der Planung der Vertriebskanäle und Partnerschaften für die Markteinführung der Software.", "answer": "falsch", "explanation": "Vertriebskanalplanung ist operativ und betrifft interne Entscheidungen, keine externen Umweltfaktoren."}

]

# Streamlit Setup
st.set_page_config(page_title="📱 Marketing Quiz", layout="centered")
st.title("📱 Marketing Quiz")
st.write("Kapitel 1.1 – 2.X | Entscheide, ob Aussagen richtig oder falsch sind.")

# Session State Initialisierung
if "shuffled_questions" not in st.session_state:
    unique_questions = list({q["question"]: q for q in questions}.values())
    st.session_state.shuffled_questions = random.sample(unique_questions, len(unique_questions))
    st.session_state.current = 0
    st.session_state.score = 0
    st.session_state.show_result = False
    st.session_state.quiz_done = False
    st.session_state.user_answer = None

# Fortschrittsanzeige
progress = st.session_state.current / len(st.session_state.shuffled_questions)
st.progress(progress)

# Quiz Logik
if not st.session_state.quiz_done and st.session_state.current < len(st.session_state.shuffled_questions):
    q = st.session_state.shuffled_questions[st.session_state.current]

    if not st.session_state.show_result:
        st.markdown(
            f"""
            <div style='font-size:20px; line-height:1.8; margin-bottom:25px;'>
                {q['question']}
            </div>
            """, unsafe_allow_html=True
        )

        col1, col2 = st.columns(2)
        with col1:
            if st.button("✅ Richtig", key=f"richtig_{st.session_state.current}"):
                st.session_state.show_result = True
                st.session_state.user_answer = "richtig"
                if q["answer"] == "richtig":
                    st.session_state.score += 1
        with col2:
            if st.button("❌ Falsch", key=f"falsch_{st.session_state.current}"):
                st.session_state.show_result = True
                st.session_state.user_answer = "falsch"
                if q["answer"] == "falsch":
                    st.session_state.score += 1

    if st.session_state.show_result:
        if st.session_state.user_answer == q["answer"]:
            st.markdown("<div style='background-color:#d4edda;padding:10px;border-radius:8px;'>✅ Deine Antwort war richtig!</div>", unsafe_allow_html=True)
        else:
            st.markdown("<div style='background-color:#f8d7da;padding:10px;border-radius:8px;'>❌ Deine Antwort war falsch!</div>", unsafe_allow_html=True)

        st.info(f"**Begründung:** {q['explanation']}")

        if st.button("➡️ Nächste Frage", key=f"next_{st.session_state.current}"):
            st.session_state.current += 1
            st.session_state.show_result = False
            st.session_state.user_answer = None
            st.rerun()

# Quiz abgeschlossen
elif not st.session_state.quiz_done:
    st.session_state.quiz_done = True
    st.success(f"✅ Quiz abgeschlossen! Ergebnis: {st.session_state.score}/{len(st.session_state.shuffled_questions)}")
    if st.button("🔁 Quiz neu starten", use_container_width=True):
        for key in ["shuffled_questions", "current", "score", "show_result", "quiz_done", "user_answer"]:
            del st.session_state[key]
        st.rerun()
